package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * AbbreviatedAnalysisData generated by hbm2java
 */
@Entity
@Table(name="abbreviated_analysis_data"
    ,schema="public"
)
public class AbbreviatedAnalysisData  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;
    @GeneratorColumn(title = "分析项目",condition=true,order=true,like=true)
    private String analyzeItem;
    @GeneratorColumn(title = "分析值")
    private String analyzeValue;
    @GeneratorColumn(title = "备注")
    private String remark;

    public AbbreviatedAnalysisData() {
    }

	
    public AbbreviatedAnalysisData(Integer id) {
        this.id = id;
    }
    public AbbreviatedAnalysisData(int id, Integer sampleId, String analyzeItem, String analyzeValue, String remark) {
       this.id = id;
       this.sampleId = sampleId;
       this.analyzeItem = analyzeItem;
       this.analyzeValue = analyzeValue;
       this.remark = remark;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="analyze_item", length=15)
    public String getAnalyzeItem() {
        return this.analyzeItem;
    }
    
    public void setAnalyzeItem(String analyzeItem) {
        this.analyzeItem = analyzeItem;
    }
    
    @Column(name="analyze_value", length=15)
    public String getAnalyzeValue() {
        return this.analyzeValue;
    }
    
    public void setAnalyzeValue(String analyzeValue) {
        this.analyzeValue = analyzeValue;
    }
    
    @Column(name="remark", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id", nullable=false)
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }


}


