package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * ArtificialHeavyMineralBasicinfo generated by hbm2java
 */
@Entity
@Table(name="artificial_heavy_mineral_basicinfo"
    ,schema="public"
)
public class ArtificialHeavyMineralBasicinfo  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private int sampleId;
    @GeneratorColumn(title = "样品重量(Kg)")
    private double sampleWeight;
    @GeneratorColumn(title = "重砂总重量(g)")
    private double heavySandWeight;
    @GeneratorColumn(title = "磁性部分重量(g)")
    private double magnetCompoWeight;
    @GeneratorColumn(title = "电磁性部分重量(g)")
    private double electromagCompoWeight;
    @GeneratorColumn(title = "重部分重量(g)")
    private double heavyCompoWeight;
    @GeneratorColumn(title = "轻部分重量(g)")
    private double lightCompoWeight;
    @GeneratorColumn(title = "备注")
    private String remark;


    public ArtificialHeavyMineralBasicinfo() {
    }


    public ArtificialHeavyMineralBasicinfo(int id, int sampleId, double sampleWeight, double heavySandWeight, double magnetCompoWeight, double electromagCompoWeight, double heavyCompoWeight, double lightCompoWeight) {
        this.id = id;
        this.sampleId = sampleId;
        this.sampleWeight = sampleWeight;
        this.heavySandWeight = heavySandWeight;
        this.magnetCompoWeight = magnetCompoWeight;
        this.electromagCompoWeight = electromagCompoWeight;
        this.heavyCompoWeight = heavyCompoWeight;
        this.lightCompoWeight = lightCompoWeight;
    }
    public ArtificialHeavyMineralBasicinfo(int id, int sampleId, double sampleWeight, double heavySandWeight, double magnetCompoWeight, double electromagCompoWeight, double heavyCompoWeight, double lightCompoWeight, String remark) {
        this.id = id;
        this.sampleId = sampleId;
        this.sampleWeight = sampleWeight;
        this.heavySandWeight = heavySandWeight;
        this.magnetCompoWeight = magnetCompoWeight;
        this.electromagCompoWeight = electromagCompoWeight;
        this.heavyCompoWeight = heavyCompoWeight;
        this.lightCompoWeight = lightCompoWeight;
        this.remark = remark;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="sample_weight", nullable=false, precision=17, scale=17)
    public double getSampleWeight() {
        return this.sampleWeight;
    }
    
    public void setSampleWeight(double sampleWeight) {
        this.sampleWeight = sampleWeight;
    }
    
    @Column(name="heavy_sand_weight", nullable=false, precision=17, scale=17)
    public double getHeavySandWeight() {
        return this.heavySandWeight;
    }
    
    public void setHeavySandWeight(double heavySandWeight) {
        this.heavySandWeight = heavySandWeight;
    }
    
    @Column(name="magnet_compo_weight", nullable=false, precision=17, scale=17)
    public double getMagnetCompoWeight() {
        return this.magnetCompoWeight;
    }
    
    public void setMagnetCompoWeight(double magnetCompoWeight) {
        this.magnetCompoWeight = magnetCompoWeight;
    }
    
    @Column(name="electromag_compo_weight", nullable=false, precision=17, scale=17)
    public double getElectromagCompoWeight() {
        return this.electromagCompoWeight;
    }
    
    public void setElectromagCompoWeight(double electromagCompoWeight) {
        this.electromagCompoWeight = electromagCompoWeight;
    }
    
    @Column(name="heavy_compo_weight", nullable=false, precision=17, scale=17)
    public double getHeavyCompoWeight() {
        return this.heavyCompoWeight;
    }
    
    public void setHeavyCompoWeight(double heavyCompoWeight) {
        this.heavyCompoWeight = heavyCompoWeight;
    }
    
    @Column(name="light_compo_weight", nullable=false, precision=17, scale=17)
    public double getLightCompoWeight() {
        return this.lightCompoWeight;
    }
    
    public void setLightCompoWeight(double lightCompoWeight) {
        this.lightCompoWeight = lightCompoWeight;
    }
    
    @Column(name="remark", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }

}


