package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * ArtificialHeavyMineralData generated by hbm2java
 */
@Entity
@Table(name="artificial_heavy_mineral_data"
    ,schema="public"
)
public class ArtificialHeavyMineralData  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;

    @GeneratorColumn(title = "矿物名称")
    private String mineralName;
    @GeneratorColumn(title = "矿物名称代号")
    private String mineralCode;
    @GeneratorColumn(title = "矿物（磁性）含量")
    private String mineralMagneticContent;
    @GeneratorColumn(title = "矿物（电磁性）含量")
    private String mineralElectromagContent;
    @GeneratorColumn(title = "矿物（重部分）含量")
    private String mineralHeavyContent;
    @GeneratorColumn(title = "矿物（轻部分）含量")
    private String mineralLightContent;
    @GeneratorColumn(title = "矿物特征描述")
    private String mineralCharacter;
    @GeneratorColumn(title = "晶形图")
    private String crystalShapeFigure;
    @GeneratorColumn(title = "基本信息")
    private Integer relId;
    public ArtificialHeavyMineralData() {
    }

    public ArtificialHeavyMineralData(int id, String mineralName) {
        this.id = id;
        this.mineralName = mineralName;
    }
    public ArtificialHeavyMineralData(int id, String mineralName, String mineralCode, String mineralMagneticContent, String mineralElectromagContent, String mineralHeavyContent, String mineralLightContent, String mineralCharacter, String crystalShapeFigure, Integer relId) {
        this.id = id;
        this.mineralName = mineralName;
        this.mineralCode = mineralCode;
        this.mineralMagneticContent = mineralMagneticContent;
        this.mineralElectromagContent = mineralElectromagContent;
        this.mineralHeavyContent = mineralHeavyContent;
        this.mineralLightContent = mineralLightContent;
        this.mineralCharacter = mineralCharacter;
        this.crystalShapeFigure = crystalShapeFigure;
        this.relId = relId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="mineral_name", nullable=false, length=40)
    public String getMineralName() {
        return this.mineralName;
    }
    
    public void setMineralName(String mineralName) {
        this.mineralName = mineralName;
    }
    
    @Column(name="mineral_code", length=15)
    public String getMineralCode() {
        return this.mineralCode;
    }
    
    public void setMineralCode(String mineralCode) {
        this.mineralCode = mineralCode;
    }
    
    @Column(name="mineral_magnetic_content", length=12)
    public String getMineralMagneticContent() {
        return this.mineralMagneticContent;
    }
    
    public void setMineralMagneticContent(String mineralMagneticContent) {
        this.mineralMagneticContent = mineralMagneticContent;
    }
    
    @Column(name="mineral_electromag__content", length=12)
    public String getMineralElectromagContent() {
        return this.mineralElectromagContent;
    }
    
    public void setMineralElectromagContent(String mineralElectromagContent) {
        this.mineralElectromagContent = mineralElectromagContent;
    }
    
    @Column(name="mineral_heavy_content", length=12)
    public String getMineralHeavyContent() {
        return this.mineralHeavyContent;
    }
    
    public void setMineralHeavyContent(String mineralHeavyContent) {
        this.mineralHeavyContent = mineralHeavyContent;
    }
    
    @Column(name="mineral_light_content", length=12)
    public String getMineralLightContent() {
        return this.mineralLightContent;
    }
    
    public void setMineralLightContent(String mineralLightContent) {
        this.mineralLightContent = mineralLightContent;
    }
    
    @Column(name="mineral_character", length=200)
    public String getMineralCharacter() {
        return this.mineralCharacter;
    }
    
    public void setMineralCharacter(String mineralCharacter) {
        this.mineralCharacter = mineralCharacter;
    }
    
    @Column(name="crystal_shape_figure", length=200)
    public String getCrystalShapeFigure() {
        return this.crystalShapeFigure;
    }
    
    public void setCrystalShapeFigure(String crystalShapeFigure) {
        this.crystalShapeFigure = crystalShapeFigure;
    }

    @Column(name="rel_id")
    public Integer getRelId() {
        return this.relId;
    }

    public void setRelId(Integer relId) {
        this.relId = relId;
    }


}


