package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name="article"
    ,schema="public"
)
public class Article  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "文章名称",condition=true,order=true,like=true)
    private String articleName;
    @GeneratorColumn(title = "引用格式")
    private String reference;
    @GeneratorColumn(title = "DOI")
    private String doi;

    public Article() {
    }

	
    public Article(Integer id) {
        this.id = id;
    }
    public Article(int id, String articleName, String reference, String doi) {
       this.id = id;
       this.articleName = articleName;
       this.reference = reference;
       this.doi = doi;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="article_name", length=200)
    public String getArticleName() {
        return this.articleName;
    }
    
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }
    
    @Column(name="reference")
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    
    @Column(name="doi", length=100)
    public String getDoi() {
        return this.doi;
    }
    
    public void setDoi(String doi) {
        this.doi = doi;
    }




}


