package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPArgonArgon generated by hbm2java
 */
@Entity
@Table(name="d_p_argon_argon"
    ,schema="public"
)
public class DPArgonArgon  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id ;
    @GeneratorColumn(title = "加热阶段次数（次）")
    private Integer NHeatStage;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double cecayconst;
    @GeneratorColumn(title = "J 值")
    private Double JValue;
    @GeneratorColumn(title = "全熔融年龄（Ma）")
    private Double fullmeltAge;
    @GeneratorColumn(title = "年龄误差1（Ma）")
    private Double ageError1;
    @GeneratorColumn(title = "坪年龄（Ma）")
    private Double plateauAge;
    @GeneratorColumn(title = "年龄误差2（Ma）")
    private Double ageError2;
    @GeneratorColumn(title = "备注")
    private String remark;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;

    public DPArgonArgon() {
    }


    public DPArgonArgon(int id) {
        this.id = id;
    }
    public DPArgonArgon(int id, Double cecayconst, Double JValue, Double fullmeltAge, Double ageError1, Double plateauAge, Double ageError2, String remark, Integer sampleId, Integer NHeatStage) {
        this.id = id;
        this.cecayconst = cecayconst;
        this.JValue = JValue;
        this.fullmeltAge = fullmeltAge;
        this.ageError1 = ageError1;
        this.plateauAge = plateauAge;
        this.ageError2 = ageError2;
        this.remark = remark;
        this.sampleId = sampleId;
        this.NHeatStage = NHeatStage;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cecayconst", precision=17, scale=17)
    public Double getCecayconst() {
        return this.cecayconst;
    }
    
    public void setCecayconst(Double cecayconst) {
        this.cecayconst = cecayconst;
    }
    
    @Column(name="j_value", precision=17, scale=17)
    public Double getJValue() {
        return this.JValue;
    }
    
    public void setJValue(Double JValue) {
        this.JValue = JValue;
    }
    
    @Column(name="fullmelt_age", precision=17, scale=17)
    public Double getFullmeltAge() {
        return this.fullmeltAge;
    }
    
    public void setFullmeltAge(Double fullmeltAge) {
        this.fullmeltAge = fullmeltAge;
    }
    
    @Column(name="age_error_1", precision=17, scale=17)
    public Double getAgeError1() {
        return this.ageError1;
    }
    
    public void setAgeError1(Double ageError1) {
        this.ageError1 = ageError1;
    }
    
    @Column(name="plateau_age", precision=17, scale=17)
    public Double getPlateauAge() {
        return this.plateauAge;
    }
    
    public void setPlateauAge(Double plateauAge) {
        this.plateauAge = plateauAge;
    }
    
    @Column(name="age_error_2", precision=17, scale=17)
    public Double getAgeError2() {
        return this.ageError2;
    }
    
    public void setAgeError2(Double ageError2) {
        this.ageError2 = ageError2;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="n_heat_stage")
    public Integer getNHeatStage() {
        return this.NHeatStage;
    }
    
    public void setNHeatStage(Integer NHeatStage) {
        this.NHeatStage = NHeatStage;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }



}


