package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPFissionTrack generated by hbm2java
 */
@Entity
@Table(name="d_p_fission_track"
    ,schema="public"
)
public class DPFissionTrack  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double decayConst;
    @GeneratorColumn(title = "裂变常数")
    private Double fissionConst;
    @GeneratorColumn(title = "径迹长度（cm）")
    private Double trackLength;
    @GeneratorColumn(title = "自发裂变径迹密度（条/cm<sup>2</sup>）")
    private Integer spontaneFissionTrackDensity;
    @GeneratorColumn(title = "热中子剂量（1/cm<sup>2</sup>））")
    private Double thermalDose;
    @GeneratorColumn(title = "人工诱发裂变径迹密度（条/cm<sup>2</sup>））")
    private Integer artificialFissionTrackDensity;
    @GeneratorColumn(title = "裂变径迹年龄（Ma）")
    private Double fissionTrackAge;
    @GeneratorColumn(title = "年龄误差（Ma）")
    private Double ageError;
    @GeneratorColumn(title = "备注")
    private String remark;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;

    public DPFissionTrack() {
    }

    public DPFissionTrack(int id) {
        this.id = id;
    }
    public DPFissionTrack(int id, Double decayConst, Double fissionConst, Double trackLength, Double thermalDose, Double fissionTrackAge, Double ageError, String remark, Integer sampleId, Integer spontaneFissionTrackDensity, Integer artificialFissionTrackDensity) {
        this.id = id;
        this.decayConst = decayConst;
        this.fissionConst = fissionConst;
        this.trackLength = trackLength;
        this.thermalDose = thermalDose;
        this.fissionTrackAge = fissionTrackAge;
        this.ageError = ageError;
        this.remark = remark;
        this.sampleId = sampleId;
        this.spontaneFissionTrackDensity = spontaneFissionTrackDensity;
        this.artificialFissionTrackDensity = artificialFissionTrackDensity;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)   @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const", precision=17, scale=17)
    public Double getDecayConst() {
        return this.decayConst;
    }
    
    public void setDecayConst(Double decayConst) {
        this.decayConst = decayConst;
    }
    
    @Column(name="fission_const", precision=17, scale=17)
    public Double getFissionConst() {
        return this.fissionConst;
    }
    
    public void setFissionConst(Double fissionConst) {
        this.fissionConst = fissionConst;
    }
    
    @Column(name="track_length", precision=17, scale=17)
    public Double getTrackLength() {
        return this.trackLength;
    }
    
    public void setTrackLength(Double trackLength) {
        this.trackLength = trackLength;
    }
    
    @Column(name="thermal_dose", precision=17, scale=17)
    public Double getThermalDose() {
        return this.thermalDose;
    }
    
    public void setThermalDose(Double thermalDose) {
        this.thermalDose = thermalDose;
    }
    
    @Column(name="fission_track_age", precision=17, scale=17)
    public Double getFissionTrackAge() {
        return this.fissionTrackAge;
    }
    
    public void setFissionTrackAge(Double fissionTrackAge) {
        this.fissionTrackAge = fissionTrackAge;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="spontane_fission_track_density")
    public Integer getSpontaneFissionTrackDensity() {
        return this.spontaneFissionTrackDensity;
    }
    
    public void setSpontaneFissionTrackDensity(Integer spontaneFissionTrackDensity) {
        this.spontaneFissionTrackDensity = spontaneFissionTrackDensity;
    }
    
    @Column(name="artificial_fission_track_density")
    public Integer getArtificialFissionTrackDensity() {
        return this.artificialFissionTrackDensity;
    }
    
    public void setArtificialFissionTrackDensity(Integer artificialFissionTrackDensity) {
        this.artificialFissionTrackDensity = artificialFissionTrackDensity;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }



}


