package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPLeadLeadEvaporation generated by hbm2java
 */
@Entity
@Table(name="d_p_lead_lead_evaporation"
    ,schema="public"
)
public class DPLeadLeadEvaporation  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "衰变常数1 （1/年）")
    private Double decayConst1;
    @GeneratorColumn(title = "衰变常数2 （1/年）")
    private Double decayConst2;
    @GeneratorColumn(title = "(Pb<sup>207</sup>/Pb<sup>206</sup>)<sub>r</sub>")
    private Double pb207Pb206r;
    @GeneratorColumn(title = "测定误差 1")
    private Double measureError1;
    @GeneratorColumn(title = "(Pb<sup>204</sup>/Pb<sup>206</sup>)<sub>m</sub>")
    private Double pb204Pb206m;
    @GeneratorColumn(title = "测定误差 2")
    private Double measureError2;
    @GeneratorColumn(title = "铅 <sup>207</sup>-铅 <sup>206</sup> 年龄（Ma）")
    private Double pb207Pb206Age;
    @GeneratorColumn(title = "年龄误差(Ma)")
    private Double ageError;
    @GeneratorColumn(title = "备注")
    private String remark;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;

    public DPLeadLeadEvaporation() {
    }

    public DPLeadLeadEvaporation(int id) {
        this.id = id;
    }
    public DPLeadLeadEvaporation(int id, Double decayConst1, Double decayConst2, Double pb207Pb206r, Double measureError1, Double pb204Pb206m, Double measureError2, Double pb207Pb206Age, Double ageError, String remark, Integer sampleId) {
        this.id = id;
        this.decayConst1 = decayConst1;
        this.decayConst2 = decayConst2;
        this.pb207Pb206r = pb207Pb206r;
        this.measureError1 = measureError1;
        this.pb204Pb206m = pb204Pb206m;
        this.measureError2 = measureError2;
        this.pb207Pb206Age = pb207Pb206Age;
        this.ageError = ageError;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const_1", precision=17, scale=17)
    public Double getDecayConst1() {
        return this.decayConst1;
    }
    
    public void setDecayConst1(Double decayConst1) {
        this.decayConst1 = decayConst1;
    }
    
    @Column(name="decay_const_2", precision=17, scale=17)
    public Double getDecayConst2() {
        return this.decayConst2;
    }
    
    public void setDecayConst2(Double decayConst2) {
        this.decayConst2 = decayConst2;
    }
    
    @Column(name="pb207_pb206r", precision=17, scale=17)
    public Double getPb207Pb206r() {
        return this.pb207Pb206r;
    }
    
    public void setPb207Pb206r(Double pb207Pb206r) {
        this.pb207Pb206r = pb207Pb206r;
    }
    
    @Column(name="measure_error_1", precision=17, scale=17)
    public Double getMeasureError1() {
        return this.measureError1;
    }
    
    public void setMeasureError1(Double measureError1) {
        this.measureError1 = measureError1;
    }
    
    @Column(name="pb204_pb206m", precision=17, scale=17)
    public Double getPb204Pb206m() {
        return this.pb204Pb206m;
    }
    
    public void setPb204Pb206m(Double pb204Pb206m) {
        this.pb204Pb206m = pb204Pb206m;
    }
    
    @Column(name="measure_error_2", precision=17, scale=17)
    public Double getMeasureError2() {
        return this.measureError2;
    }
    
    public void setMeasureError2(Double measureError2) {
        this.measureError2 = measureError2;
    }
    
    @Column(name="pb207_pb206_age", precision=17, scale=17)
    public Double getPb207Pb206Age() {
        return this.pb207Pb206Age;
    }
    
    public void setPb207Pb206Age(Double pb207Pb206Age) {
        this.pb207Pb206Age = pb207Pb206Age;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }


}


