package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPOrdinaryLead generated by hbm2java
 */
@Entity
@Table(name="d_p_ordinary_lead"
    ,schema="public"
)
public class DPOrdinaryLead  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;
    @GeneratorColumn(title = "矿物特征")
    private String mineralCharacter;
    @GeneratorColumn(title = "衰变常数1 （1/年）")
    private Double decayConst1;
    @GeneratorColumn(title = "衰变常数2 （1/年）")
    private Double decayConst2;
    @GeneratorColumn(title = "<sup>206</sup>Pb/<sup>204</sup>Pb")
    private Double pb206Pb204;
    @GeneratorColumn(title = "<sup>207</sup>Pb/<sup>204</sup>Pb")
    private Double pb207Pb204;
    @GeneratorColumn(title = "<sup>208</sup>Pb/<sup>204</sup>Pb")
    private Double pb208Pb204;
    @GeneratorColumn(title = "模式年龄 1（Ma）")
    private Double modelAge1;
    @GeneratorColumn(title = "模式年龄 1误差（Ma）")
    private Double modelAge1Error;
    @GeneratorColumn(title = "模式年龄2（Ma）")
    private Double modelAge2;
    @GeneratorColumn(title = "模式年龄 2误差（Ma）")
    private Double modelAge2Error;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPOrdinaryLead() {
    }


    public DPOrdinaryLead(int id) {
        this.id = id;
    }
    public DPOrdinaryLead(int id, String mineralCharacter, Double decayConst1, Double decayConst2, Double pb206Pb204, Double pb207Pb204, Double pb208Pb204, Double modelAge1, Double modelAge1Error, Double modelAge2, Double modelAge2Error, String remark, Integer sampleId) {
        this.id = id;
        this.mineralCharacter = mineralCharacter;
        this.decayConst1 = decayConst1;
        this.decayConst2 = decayConst2;
        this.pb206Pb204 = pb206Pb204;
        this.pb207Pb204 = pb207Pb204;
        this.pb208Pb204 = pb208Pb204;
        this.modelAge1 = modelAge1;
        this.modelAge1Error = modelAge1Error;
        this.modelAge2 = modelAge2;
        this.modelAge2Error = modelAge2Error;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="mineral_character", length=30)
    public String getMineralCharacter() {
        return this.mineralCharacter;
    }
    
    public void setMineralCharacter(String mineralCharacter) {
        this.mineralCharacter = mineralCharacter;
    }
    
    @Column(name="decay_const_1", precision=17, scale=17)
    public Double getDecayConst1() {
        return this.decayConst1;
    }
    
    public void setDecayConst1(Double decayConst1) {
        this.decayConst1 = decayConst1;
    }
    
    @Column(name="decay_const_2", precision=17, scale=17)
    public Double getDecayConst2() {
        return this.decayConst2;
    }
    
    public void setDecayConst2(Double decayConst2) {
        this.decayConst2 = decayConst2;
    }
    
    @Column(name="pb206_pb204", precision=17, scale=17)
    public Double getPb206Pb204() {
        return this.pb206Pb204;
    }
    
    public void setPb206Pb204(Double pb206Pb204) {
        this.pb206Pb204 = pb206Pb204;
    }
    
    @Column(name="pb207_pb204", precision=17, scale=17)
    public Double getPb207Pb204() {
        return this.pb207Pb204;
    }
    
    public void setPb207Pb204(Double pb207Pb204) {
        this.pb207Pb204 = pb207Pb204;
    }
    
    @Column(name="pb208_pb204", precision=17, scale=17)
    public Double getPb208Pb204() {
        return this.pb208Pb204;
    }
    
    public void setPb208Pb204(Double pb208Pb204) {
        this.pb208Pb204 = pb208Pb204;
    }
    
    @Column(name="model_age_1", precision=17, scale=17)
    public Double getModelAge1() {
        return this.modelAge1;
    }
    
    public void setModelAge1(Double modelAge1) {
        this.modelAge1 = modelAge1;
    }
    
    @Column(name="model_age_1_error", precision=17, scale=17)
    public Double getModelAge1Error() {
        return this.modelAge1Error;
    }
    
    public void setModelAge1Error(Double modelAge1Error) {
        this.modelAge1Error = modelAge1Error;
    }
    
    @Column(name="model_age_2", precision=17, scale=17)
    public Double getModelAge2() {
        return this.modelAge2;
    }
    
    public void setModelAge2(Double modelAge2) {
        this.modelAge2 = modelAge2;
    }
    
    @Column(name="model_age_2_error", precision=17, scale=17)
    public Double getModelAge2Error() {
        return this.modelAge2Error;
    }
    
    public void setModelAge2Error(Double modelAge2Error) {
        this.modelAge2Error = modelAge2Error;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }


}


