package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPOsmium generated by hbm2java
 */
@Entity
@Table(name="d_p_osmium"
    ,schema="public"
)
public class DPOsmium  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double decayConst;
    @GeneratorColumn(title = "<sup>187</sup>Os/<sup>186</sup>Os")
    private Double os187Os186;
    @GeneratorColumn(title = "<sup>187</sup>Os/<sup>188</sup>Os")
    private Double os187Os188;
    @GeneratorColumn(title = "模式年龄1（Ma）")
    private Double modelAge1;
    @GeneratorColumn(title = "模式年龄1误差(Ma)")
    private Double modelAge1Error;
    @GeneratorColumn(title = "模式年龄2（Ma）")
    private Double modelAge2;
    @GeneratorColumn(title = "模式年龄2误差(Ma)")
    private Double modelAge2Error;
    @GeneratorColumn(title = "采用年龄（Ma）")
    private Double acceptedAge;
    @GeneratorColumn(title = "采用年龄误差(Ma)")
    private Double acceptedAgeError;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPOsmium() {
    }

    public DPOsmium(int id) {
        this.id = id;
    }
    public DPOsmium(int id, Double decayConst, Double os187Os186, Double os187Os188, Double modelAge1, Double modelAge1Error, Double modelAge2, Double modelAge2Error, Double acceptedAge, Double acceptedAgeError, String remark, Integer sampleId) {
        this.id = id;
        this.decayConst = decayConst;
        this.os187Os186 = os187Os186;
        this.os187Os188 = os187Os188;
        this.modelAge1 = modelAge1;
        this.modelAge1Error = modelAge1Error;
        this.modelAge2 = modelAge2;
        this.modelAge2Error = modelAge2Error;
        this.acceptedAge = acceptedAge;
        this.acceptedAgeError = acceptedAgeError;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const", precision=17, scale=17)
    public Double getDecayConst() {
        return this.decayConst;
    }
    
    public void setDecayConst(Double decayConst) {
        this.decayConst = decayConst;
    }
    
    @Column(name="os187_os186", precision=17, scale=17)
    public Double getOs187Os186() {
        return this.os187Os186;
    }
    
    public void setOs187Os186(Double os187Os186) {
        this.os187Os186 = os187Os186;
    }
    
    @Column(name="os187_os188", precision=17, scale=17)
    public Double getOs187Os188() {
        return this.os187Os188;
    }
    
    public void setOs187Os188(Double os187Os188) {
        this.os187Os188 = os187Os188;
    }
    
    @Column(name="model_age_1", precision=17, scale=17)
    public Double getModelAge1() {
        return this.modelAge1;
    }
    
    public void setModelAge1(Double modelAge1) {
        this.modelAge1 = modelAge1;
    }
    
    @Column(name="model_age_1_error", precision=17, scale=17)
    public Double getModelAge1Error() {
        return this.modelAge1Error;
    }
    
    public void setModelAge1Error(Double modelAge1Error) {
        this.modelAge1Error = modelAge1Error;
    }
    
    @Column(name="model_age_2", precision=17, scale=17)
    public Double getModelAge2() {
        return this.modelAge2;
    }
    
    public void setModelAge2(Double modelAge2) {
        this.modelAge2 = modelAge2;
    }
    
    @Column(name="model_age_2_error", precision=17, scale=17)
    public Double getModelAge2Error() {
        return this.modelAge2Error;
    }
    
    public void setModelAge2Error(Double modelAge2Error) {
        this.modelAge2Error = modelAge2Error;
    }
    
    @Column(name="accepted_age", precision=17, scale=17)
    public Double getAcceptedAge() {
        return this.acceptedAge;
    }
    
    public void setAcceptedAge(Double acceptedAge) {
        this.acceptedAge = acceptedAge;
    }
    
    @Column(name="accepted_age_error", precision=17, scale=17)
    public Double getAcceptedAgeError() {
        return this.acceptedAgeError;
    }
    
    public void setAcceptedAgeError(Double acceptedAgeError) {
        this.acceptedAgeError = acceptedAgeError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }


}


