package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPPotassiumArgon generated by hbm2java
 */
@Entity
@Table(name="d_p_potassium_argon"
    ,schema="public"
)
public class DPPotassiumArgon  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private int sampleId;
    @GeneratorColumn(title = "衰变常数 1（1/年）")
    private Double decayConst1;
    @GeneratorColumn(title = "衰变常数 2（1/年）")
    private Double decayConst2;
    @GeneratorColumn(title = "钾（%）")
    private Double k;
    @GeneratorColumn(title = "氩-40（10<sup>-6</sup>）")
    private Double ar40;
    @GeneratorColumn(title = "大气氩（%）")
    private Double atmospArgon;
    @GeneratorColumn(title = "<sup>40</sup>Ar/<sup>40</sup>K")
    private Double ar40K40;
    @GeneratorColumn(title = "<sup>40</sup>Ar/<sup>36</sup>Ar ")
    private Double ar40Ar36;
    @GeneratorColumn(title = "钾-氩年龄（Ma）")
    private Double age;
    @GeneratorColumn(title = "年龄误差（Ma）")
    private Double ageError;
    @GeneratorColumn(title = "备注")
    private Double remark;

    public DPPotassiumArgon() {
    }

    public DPPotassiumArgon(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public DPPotassiumArgon(int id, Double decayConst1, Double decayConst2, Double k, Double ar40, Double atmospArgon, Double ar40K40, Double ar40Ar36, Double age, Double ageError, Double remark, int sampleId) {
        this.id = id;
        this.decayConst1 = decayConst1;
        this.decayConst2 = decayConst2;
        this.k = k;
        this.ar40 = ar40;
        this.atmospArgon = atmospArgon;
        this.ar40K40 = ar40K40;
        this.ar40Ar36 = ar40Ar36;
        this.age = age;
        this.ageError = ageError;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="decay_const_1", precision=17, scale=17)
    public Double getDecayConst1() {
        return this.decayConst1;
    }
    
    public void setDecayConst1(Double decayConst1) {
        this.decayConst1 = decayConst1;
    }
    
    @Column(name="decay_const_2", precision=17, scale=17)
    public Double getDecayConst2() {
        return this.decayConst2;
    }
    
    public void setDecayConst2(Double decayConst2) {
        this.decayConst2 = decayConst2;
    }
    
    @Column(name="k", precision=17, scale=17)
    public Double getK() {
        return this.k;
    }
    
    public void setK(Double k) {
        this.k = k;
    }
    
    @Column(name="ar40", precision=17, scale=17)
    public Double getAr40() {
        return this.ar40;
    }
    
    public void setAr40(Double ar40) {
        this.ar40 = ar40;
    }
    
    @Column(name="atmosp_argon", precision=17, scale=17)
    public Double getAtmospArgon() {
        return this.atmospArgon;
    }
    
    public void setAtmospArgon(Double atmospArgon) {
        this.atmospArgon = atmospArgon;
    }
    
    @Column(name="ar40_k40", precision=17, scale=17)
    public Double getAr40K40() {
        return this.ar40K40;
    }
    
    public void setAr40K40(Double ar40K40) {
        this.ar40K40 = ar40K40;
    }
    
    @Column(name="ar40_ar36", precision=17, scale=17)
    public Double getAr40Ar36() {
        return this.ar40Ar36;
    }
    
    public void setAr40Ar36(Double ar40Ar36) {
        this.ar40Ar36 = ar40Ar36;
    }
    
    @Column(name="age", precision=17, scale=17)
    public Double getAge() {
        return this.age;
    }
    
    public void setAge(Double age) {
        this.age = age;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="remark", precision=17, scale=17)
    public Double getRemark() {
        return this.remark;
    }
    
    public void setRemark(Double remark) {
        this.remark = remark;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }


}


