package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPRbSr generated by hbm2java
 */
@Entity
@Table(name="d_p_rb_sr"
    ,schema="public"
)
public class DPRbSr  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品")
    private int sampleId;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double decayConst;
    @GeneratorColumn(title = "铷(10<sup>-6</sup>)")
    private Double rb;
    @GeneratorColumn(title = "锶（10<sup>-6</sup>）")
    private Double sr;
    @GeneratorColumn(title = "<sup>87</sup>Rb／<sup>86</sup>Sr")
    private Double rb87Sr86;
    @GeneratorColumn(title = "<sup>87</sup>Sr／<sup>86</sup>Sr")
    private Double sr87Sr86;
    @GeneratorColumn(title = "表面年龄（Ma）")
    private Double surfaceAge;
    @GeneratorColumn(title = "表面年龄误差（Ma）")
    private Double surfaceAgeError;
    @GeneratorColumn(title = "模式年龄（Ma）")
    private Double modelAge;
    @GeneratorColumn(title = "模式年龄误差(Ma)")
    private Double modelAgeError;
    @GeneratorColumn(title = "εSr(o)")
    private Double epsilonSrO;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPRbSr() {
    }


    public DPRbSr(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public DPRbSr(int id, Double decayConst, Double rb, Double sr, Double rb87Sr86, Double sr87Sr86, Double surfaceAge, Double surfaceAgeError, Double modelAge, Double modelAgeError, Double epsilonSrO, int sampleId, String remark) {
        this.id = id;
        this.decayConst = decayConst;
        this.rb = rb;
        this.sr = sr;
        this.rb87Sr86 = rb87Sr86;
        this.sr87Sr86 = sr87Sr86;
        this.surfaceAge = surfaceAge;
        this.surfaceAgeError = surfaceAgeError;
        this.modelAge = modelAge;
        this.modelAgeError = modelAgeError;
        this.epsilonSrO = epsilonSrO;
        this.sampleId = sampleId;
        this.remark = remark;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const", precision=17, scale=17)
    public Double getDecayConst() {
        return this.decayConst;
    }
    
    public void setDecayConst(Double decayConst) {
        this.decayConst = decayConst;
    }
    
    @Column(name="rb", precision=17, scale=17)
    public Double getRb() {
        return this.rb;
    }
    
    public void setRb(Double rb) {
        this.rb = rb;
    }
    
    @Column(name="sr", precision=17, scale=17)
    public Double getSr() {
        return this.sr;
    }
    
    public void setSr(Double sr) {
        this.sr = sr;
    }
    
    @Column(name="rb87_sr86", precision=17, scale=17)
    public Double getRb87Sr86() {
        return this.rb87Sr86;
    }
    
    public void setRb87Sr86(Double rb87Sr86) {
        this.rb87Sr86 = rb87Sr86;
    }
    
    @Column(name="sr87_sr86", precision=17, scale=17)
    public Double getSr87Sr86() {
        return this.sr87Sr86;
    }
    
    public void setSr87Sr86(Double sr87Sr86) {
        this.sr87Sr86 = sr87Sr86;
    }
    
    @Column(name="surface_age", precision=17, scale=17)
    public Double getSurfaceAge() {
        return this.surfaceAge;
    }
    
    public void setSurfaceAge(Double surfaceAge) {
        this.surfaceAge = surfaceAge;
    }
    
    @Column(name="surface_age_error", precision=17, scale=17)
    public Double getSurfaceAgeError() {
        return this.surfaceAgeError;
    }
    
    public void setSurfaceAgeError(Double surfaceAgeError) {
        this.surfaceAgeError = surfaceAgeError;
    }
    
    @Column(name="model_age", precision=17, scale=17)
    public Double getModelAge() {
        return this.modelAge;
    }
    
    public void setModelAge(Double modelAge) {
        this.modelAge = modelAge;
    }
    
    @Column(name="model_age_error", precision=17, scale=17)
    public Double getModelAgeError() {
        return this.modelAgeError;
    }
    
    public void setModelAgeError(Double modelAgeError) {
        this.modelAgeError = modelAgeError;
    }
    
    @Column(name="epsilon_sr_o", precision=17, scale=17)
    public Double getEpsilonSrO() {
        return this.epsilonSrO;
    }
    
    public void setEpsilonSrO(Double epsilonSrO) {
        this.epsilonSrO = epsilonSrO;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }


}


