package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPReOsmium generated by hbm2java
 */
@Entity
@Table(name="d_p_re_osmium"
    ,schema="public"
)
public class DPReOsmium  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double decayConst;
    @GeneratorColumn(title = "铼（10<sup>-6</sup>）")
    private Double re;
    @GeneratorColumn(title = "锇-187（10<sup>-6</sup>）")
    private Double os187;
    @GeneratorColumn(title = "模式年龄（Ma）")
    private Double modelAge;
    @GeneratorColumn(title = "年龄误差(Ma)")
    private Double ageError;
    @GeneratorColumn(title = "备注")
    private String remark;
    @GeneratorColumn(title = "样品")
    private Integer sampleId;
    public DPReOsmium() {
    }


    public DPReOsmium(int id) {
        this.id = id;
    }
    public DPReOsmium(int id, Double decayConst, Double re, Double os187, Double modelAge, Double ageError, String remark, Integer sampleId) {
        this.id = id;
        this.decayConst = decayConst;
        this.re = re;
        this.os187 = os187;
        this.modelAge = modelAge;
        this.ageError = ageError;
        this.remark = remark;
        this.sampleId = sampleId;
    }


    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const", precision=17, scale=17)
    public Double getDecayConst() {
        return this.decayConst;
    }
    
    public void setDecayConst(Double decayConst) {
        this.decayConst = decayConst;
    }
    
    @Column(name="re", precision=17, scale=17)
    public Double getRe() {
        return this.re;
    }
    
    public void setRe(Double re) {
        this.re = re;
    }
    
    @Column(name="os_187", precision=17, scale=17)
    public Double getOs187() {
        return this.os187;
    }
    
    public void setOs187(Double os187) {
        this.os187 = os187;
    }
    
    @Column(name="model_age", precision=17, scale=17)
    public Double getModelAge() {
        return this.modelAge;
    }
    
    public void setModelAge(Double modelAge) {
        this.modelAge = modelAge;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }


}


