package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPSamariumNeodymium generated by hbm2java
 */
@Entity
@Table(name="d_p_samarium_neodymium"
    ,schema="public"
)
public class DPSamariumNeodymium  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "衰变常数 （1/年）")
    private Double decayConst;
    @GeneratorColumn(title = "钐(10<sup>-6</sup>)")
    private Double sm;
    @GeneratorColumn(title = "钕（10<sup>-6</sup>）")
    private Double nd;
    @GeneratorColumn(title = "<sup>147</sup>Sm／<sup>144</sup>Nd")
    private Double sm147Nd144;
    @GeneratorColumn(title = "<sup>143</sup>Nd／<sup>144</sup>Nd")
    private Double nd143Nd144;
    @GeneratorColumn(title = "模式年龄（Ma）")
    private Double modelAge;
    @GeneratorColumn(title = "年龄误差(Ma)")
    private Double ageError;
    @GeneratorColumn(title = "εNd(o)")
    private Double epsilonNdO;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPSamariumNeodymium() {
    }


    public DPSamariumNeodymium(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public DPSamariumNeodymium(int id, Double decayConst, Double sm, Double nd, Double sm147Nd144, Double nd143Nd144, Double modelAge, Double ageError, Double epsilonNdO, String remark, int sampleId) {
        this.id = id;
        this.decayConst = decayConst;
        this.sm = sm;
        this.nd = nd;
        this.sm147Nd144 = sm147Nd144;
        this.nd143Nd144 = nd143Nd144;
        this.modelAge = modelAge;
        this.ageError = ageError;
        this.epsilonNdO = epsilonNdO;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="decay_const", precision=17, scale=17)
    public Double getDecayConst() {
        return this.decayConst;
    }
    
    public void setDecayConst(Double decayConst) {
        this.decayConst = decayConst;
    }
    
    @Column(name="sm", precision=17, scale=17)
    public Double getSm() {
        return this.sm;
    }
    
    public void setSm(Double sm) {
        this.sm = sm;
    }
    
    @Column(name="nd", precision=17, scale=17)
    public Double getNd() {
        return this.nd;
    }
    
    public void setNd(Double nd) {
        this.nd = nd;
    }
    
    @Column(name="sm147_nd144", precision=17, scale=17)
    public Double getSm147Nd144() {
        return this.sm147Nd144;
    }
    
    public void setSm147Nd144(Double sm147Nd144) {
        this.sm147Nd144 = sm147Nd144;
    }
    
    @Column(name="nd143_nd144", precision=17, scale=17)
    public Double getNd143Nd144() {
        return this.nd143Nd144;
    }
    
    public void setNd143Nd144(Double nd143Nd144) {
        this.nd143Nd144 = nd143Nd144;
    }
    
    @Column(name="model_age", precision=17, scale=17)
    public Double getModelAge() {
        return this.modelAge;
    }
    
    public void setModelAge(Double modelAge) {
        this.modelAge = modelAge;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="epsilon_nd_o", precision=17, scale=17)
    public Double getEpsilonNdO() {
        return this.epsilonNdO;
    }
    
    public void setEpsilonNdO(Double epsilonNdO) {
        this.epsilonNdO = epsilonNdO;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }
}


