package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPThermoluminescence generated by hbm2java
 */
@Entity
@Table(name="d_p_thermoluminescence"
    ,schema="public"
)
public class DPThermoluminescence  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "U（10<sup>-6</sup>）")
    private Double u;
    @GeneratorColumn(title = "Th（10<sup>-6</sup>）")
    private Double th;
    @GeneratorColumn(title = "K(%)")
    private Double k;
    @GeneratorColumn(title = "古剂量（Gy）")
    private Double paleoDose;
    @GeneratorColumn(title = "年剂量率(Gy/a)")
    private Double annualDoseRate;
    @GeneratorColumn(title = "热释光年龄(ka)")
    private Double tiAge;
    @GeneratorColumn(title = "年龄误差(ka)")
    private Double ageError;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPThermoluminescence() {
    }


    public DPThermoluminescence(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public DPThermoluminescence(int id, Double u, Double th, Double k, Double paleoDose, Double annualDoseRate, Double tiAge, Double ageError, String remark, int sampleId) {
        this.id = id;
        this.u = u;
        this.th = th;
        this.k = k;
        this.paleoDose = paleoDose;
        this.annualDoseRate = annualDoseRate;
        this.tiAge = tiAge;
        this.ageError = ageError;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }

    @Column(name="u", precision=17, scale=17)
    public Double getU() {
        return this.u;
    }
    
    public void setU(Double u) {
        this.u = u;
    }
    
    @Column(name="th", precision=17, scale=17)
    public Double getTh() {
        return this.th;
    }
    
    public void setTh(Double th) {
        this.th = th;
    }
    
    @Column(name="k", precision=17, scale=17)
    public Double getK() {
        return this.k;
    }
    
    public void setK(Double k) {
        this.k = k;
    }
    
    @Column(name="Paleo_dose", precision=17, scale=17)
    public Double getPaleoDose() {
        return this.paleoDose;
    }
    
    public void setPaleoDose(Double paleoDose) {
        this.paleoDose = paleoDose;
    }
    
    @Column(name="annual_dose_rate", precision=17, scale=17)
    public Double getAnnualDoseRate() {
        return this.annualDoseRate;
    }
    
    public void setAnnualDoseRate(Double annualDoseRate) {
        this.annualDoseRate = annualDoseRate;
    }
    
    @Column(name="ti_age", precision=17, scale=17)
    public Double getTiAge() {
        return this.tiAge;
    }
    
    public void setTiAge(Double tiAge) {
        this.tiAge = tiAge;
    }
    
    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }
    
    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


