package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * DPUraniumThoriumLead generated by hbm2java
 */
@Entity
@Table(name="d_p_uranium_thorium_lead"
    ,schema="public"
)
public class DPUraniumThoriumLead  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "矿物特征")
    private String mineralCharacter;
    @GeneratorColumn(title = "衰变常数1 （1/年）")
    private Double decayConst1;
    @GeneratorColumn(title = "衰变常数2 （1/年）")
    private Double decayConst2;
    @GeneratorColumn(title = "衰变常数3 （1/年）")
    private Double decayConst3;
    @GeneratorColumn(title = "铀(10<sup>-6</sup>)")
    private Double u;
    @GeneratorColumn(title = "钍（10<sup>-6</sup>）")
    private Double th;
    @GeneratorColumn(title = "铅（10<sup>-6</sup>）")
    private Double pb;
    @GeneratorColumn(title = "铅-204（%）")
    private Double pb204;
    @GeneratorColumn(title = "铅-206（%）")
    private Double pb206;
    @GeneratorColumn(title = "铅-207（%）")
    private Double pb207;
    @GeneratorColumn(title = "铅-208（%）")
    private Double pb208;
    @GeneratorColumn(title = "<sup>206</sup>Pb/<sup>204</sup>Pb")
    private Double pb206Pb204;
    @GeneratorColumn(title = "<sup>208</sup>Pb/<sup>206</sup>Pb")
    private Double pb208Pb206;
    @GeneratorColumn(title = "<sup>207</sup>Pb/<sup>206</sup>Pb")
    private Double pb207Pb206;
    @GeneratorColumn(title = "<sup>206</sup>Pb/<sup>238</sup>U")
    private Double pb206U238;
    @GeneratorColumn(title = "<sup>207</sup>Pb/<sup>235</sup>U")
    private Double pb207U235;
    @GeneratorColumn(title = "<sup>208</sup>Pb/<sup>232</sup>Th")
    private Double pb208Th232;
    @GeneratorColumn(title = "铅<sup>-206</sup>-铀<sup>-238</sup> 年龄（Ma）")
    private Double pb206U238Age;
    @GeneratorColumn(title = "铅<sup>-206</sup>-铀<sup>-238</sup> 年龄误差（Ma）")
    private Double pb206U238AgeError;
    @GeneratorColumn(title = "铅<sup>-207</sup>-铀<sup>-235</sup> 年龄（Ma）")
    private Double pb207U235Age;
    @GeneratorColumn(title = "铅<sup>-207</sup>-铀<sup>-235</sup> 年龄误差(Ma)")
    private Double pb207U235AgeError;
    @GeneratorColumn(title = "铅<sup>-207</sup>-铅<sup>-206</sup> 年龄（Ma）")
    private Double pb207Pb206Age;
    @GeneratorColumn(title = "铅<sup>-207</sup>-铅<sup>-206</sup> 年龄误差（Ma）")
    private Double pb207Pb206AgeError;
    @GeneratorColumn(title = "铅<sup>-208</sup>-钍<sup>-232</sup> 年龄（Ma）")
    private Double pb208Th232Age;
    @GeneratorColumn(title = "铅<sup>-208</sup>-钍<sup>-232</sup> 年龄误差（Ma）")
    private Double pb208Th232AgeError;
    @GeneratorColumn(title = "备注")
    private String remark;

    public DPUraniumThoriumLead() {
    }


    public DPUraniumThoriumLead(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public DPUraniumThoriumLead(int id, String mineralCharacter, Double decayConst1, Double decayConst2, Double decayConst3, Double u, Double th, Double pb, Double pb204, Double pb206, Double pb207, Double pb208, Double pb206Pb204, Double pb208Pb206, Double pb207Pb206, Double pb206U238, Double pb207U235, Double pb208Th232, Double pb206U238Age, Double pb206U238AgeError, Double pb207U235Age, Double pb207U235AgeError, Double pb207Pb206Age, Double pb207Pb206AgeError, Double pb208Th232Age, Double pb208Th232AgeError, String remark, int sampleId) {
        this.id = id;
        this.mineralCharacter = mineralCharacter;
        this.decayConst1 = decayConst1;
        this.decayConst2 = decayConst2;
        this.decayConst3 = decayConst3;
        this.u = u;
        this.th = th;
        this.pb = pb;
        this.pb204 = pb204;
        this.pb206 = pb206;
        this.pb207 = pb207;
        this.pb208 = pb208;
        this.pb206Pb204 = pb206Pb204;
        this.pb208Pb206 = pb208Pb206;
        this.pb207Pb206 = pb207Pb206;
        this.pb206U238 = pb206U238;
        this.pb207U235 = pb207U235;
        this.pb208Th232 = pb208Th232;
        this.pb206U238Age = pb206U238Age;
        this.pb206U238AgeError = pb206U238AgeError;
        this.pb207U235Age = pb207U235Age;
        this.pb207U235AgeError = pb207U235AgeError;
        this.pb207Pb206Age = pb207Pb206Age;
        this.pb207Pb206AgeError = pb207Pb206AgeError;
        this.pb208Th232Age = pb208Th232Age;
        this.pb208Th232AgeError = pb208Th232AgeError;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }

    @Column(name="mineral_character", length=30)
    public String getMineralCharacter() {
        return this.mineralCharacter;
    }
    
    public void setMineralCharacter(String mineralCharacter) {
        this.mineralCharacter = mineralCharacter;
    }
    
    @Column(name="decay_const_1", precision=17, scale=17)
    public Double getDecayConst1() {
        return this.decayConst1;
    }
    
    public void setDecayConst1(Double decayConst1) {
        this.decayConst1 = decayConst1;
    }
    
    @Column(name="decay_const_2", precision=17, scale=17)
    public Double getDecayConst2() {
        return this.decayConst2;
    }
    
    public void setDecayConst2(Double decayConst2) {
        this.decayConst2 = decayConst2;
    }
    
    @Column(name="decay_const_3", precision=17, scale=17)
    public Double getDecayConst3() {
        return this.decayConst3;
    }
    
    public void setDecayConst3(Double decayConst3) {
        this.decayConst3 = decayConst3;
    }
    
    @Column(name="u", precision=17, scale=17)
    public Double getU() {
        return this.u;
    }
    
    public void setU(Double u) {
        this.u = u;
    }
    
    @Column(name="th", precision=17, scale=17)
    public Double getTh() {
        return this.th;
    }
    
    public void setTh(Double th) {
        this.th = th;
    }
    
    @Column(name="pb", precision=17, scale=17)
    public Double getPb() {
        return this.pb;
    }
    
    public void setPb(Double pb) {
        this.pb = pb;
    }
    
    @Column(name="pb204", precision=17, scale=17)
    public Double getPb204() {
        return this.pb204;
    }
    
    public void setPb204(Double pb204) {
        this.pb204 = pb204;
    }
    
    @Column(name="pb206", precision=17, scale=17)
    public Double getPb206() {
        return this.pb206;
    }
    
    public void setPb206(Double pb206) {
        this.pb206 = pb206;
    }
    
    @Column(name="pb207", precision=17, scale=17)
    public Double getPb207() {
        return this.pb207;
    }
    
    public void setPb207(Double pb207) {
        this.pb207 = pb207;
    }
    
    @Column(name="pb208", precision=17, scale=17)
    public Double getPb208() {
        return this.pb208;
    }
    
    public void setPb208(Double pb208) {
        this.pb208 = pb208;
    }
    
    @Column(name="pb206_pb204", precision=17, scale=17)
    public Double getPb206Pb204() {
        return this.pb206Pb204;
    }
    
    public void setPb206Pb204(Double pb206Pb204) {
        this.pb206Pb204 = pb206Pb204;
    }
    
    @Column(name="pb208_pb206", precision=17, scale=17)
    public Double getPb208Pb206() {
        return this.pb208Pb206;
    }
    
    public void setPb208Pb206(Double pb208Pb206) {
        this.pb208Pb206 = pb208Pb206;
    }
    
    @Column(name="pb207_pb206", precision=17, scale=17)
    public Double getPb207Pb206() {
        return this.pb207Pb206;
    }
    
    public void setPb207Pb206(Double pb207Pb206) {
        this.pb207Pb206 = pb207Pb206;
    }
    
    @Column(name="pb206_u238", precision=17, scale=17)
    public Double getPb206U238() {
        return this.pb206U238;
    }
    
    public void setPb206U238(Double pb206U238) {
        this.pb206U238 = pb206U238;
    }
    
    @Column(name="pb207_u235", precision=17, scale=17)
    public Double getPb207U235() {
        return this.pb207U235;
    }
    
    public void setPb207U235(Double pb207U235) {
        this.pb207U235 = pb207U235;
    }
    
    @Column(name="pb208_th232", precision=17, scale=17)
    public Double getPb208Th232() {
        return this.pb208Th232;
    }
    
    public void setPb208Th232(Double pb208Th232) {
        this.pb208Th232 = pb208Th232;
    }
    
    @Column(name="pb206_u238_age", precision=17, scale=17)
    public Double getPb206U238Age() {
        return this.pb206U238Age;
    }
    
    public void setPb206U238Age(Double pb206U238Age) {
        this.pb206U238Age = pb206U238Age;
    }
    
    @Column(name="pb206_u238_age_error", precision=17, scale=17)
    public Double getPb206U238AgeError() {
        return this.pb206U238AgeError;
    }
    
    public void setPb206U238AgeError(Double pb206U238AgeError) {
        this.pb206U238AgeError = pb206U238AgeError;
    }
    
    @Column(name="pb207_u235_age", precision=17, scale=17)
    public Double getPb207U235Age() {
        return this.pb207U235Age;
    }
    
    public void setPb207U235Age(Double pb207U235Age) {
        this.pb207U235Age = pb207U235Age;
    }
    
    @Column(name="pb207_u235_age_error", precision=17, scale=17)
    public Double getPb207U235AgeError() {
        return this.pb207U235AgeError;
    }
    
    public void setPb207U235AgeError(Double pb207U235AgeError) {
        this.pb207U235AgeError = pb207U235AgeError;
    }
    
    @Column(name="pb207_pb206_age", precision=17, scale=17)
    public Double getPb207Pb206Age() {
        return this.pb207Pb206Age;
    }
    
    public void setPb207Pb206Age(Double pb207Pb206Age) {
        this.pb207Pb206Age = pb207Pb206Age;
    }
    
    @Column(name="pb207_pb206_age_error", precision=17, scale=17)
    public Double getPb207Pb206AgeError() {
        return this.pb207Pb206AgeError;
    }
    
    public void setPb207Pb206AgeError(Double pb207Pb206AgeError) {
        this.pb207Pb206AgeError = pb207Pb206AgeError;
    }
    
    @Column(name="pb208_th232_age", precision=17, scale=17)
    public Double getPb208Th232Age() {
        return this.pb208Th232Age;
    }
    
    public void setPb208Th232Age(Double pb208Th232Age) {
        this.pb208Th232Age = pb208Th232Age;
    }
    
    @Column(name="pb208_th232_age_error", precision=17, scale=17)
    public Double getPb208Th232AgeError() {
        return this.pb208Th232AgeError;
    }
    
    public void setPb208Th232AgeError(Double pb208Th232AgeError) {
        this.pb208Th232AgeError = pb208Th232AgeError;
    }
    
    @Column(name="remark", length=80)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


