package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * EpmaData generated by hbm2java
 */
@Entity
@Table(name="epma_data"
    ,schema="public"
)
public class EpmaData  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "矿物名称")
    private String mineralName;
    @GeneratorColumn(title = "SiO<sub>2</sub>（10<sup>-2</sup>）")
    private Double siO2;
    @GeneratorColumn(title = "TiO<sub>2</sub> (10<sup>-2</sup>）")
    private Double tiO2;
    @GeneratorColumn(title = "Al<sub>2</sub>O<sub>3</sub>(10<sup>-2</sup>）")
    private Double al2O3;
    @GeneratorColumn(title = "Cr<sub>2</sub>O<sub>3</sub>(10<sup>-2</sup>）")
    private Double cr2O3;
    @GeneratorColumn(title = "Fe<sub>2</sub>O<sub>3</sub>(10<sup>-2</sup>）")
    private Double fe2O3;
    @GeneratorColumn(title = "FeO(10<sup>-2</sup>)")
    private Double feO;
    @GeneratorColumn(title = "NiO(10<sup>-2</sup>)")
    private Double niO;
    @GeneratorColumn(title = "MnO(10<sup>-2</sup>)")
    private Double mnO;
    @GeneratorColumn(title = "MgO(10<sup>-2</sup>)")
    private Double mgO;
    @GeneratorColumn(title = "CaO(10<sup>-2</sup>)")
    private Double caO;
    @GeneratorColumn(title = "Na<sub>2</sub>O(10<sup>-2</sup>)")
    private Double na2O;
    @GeneratorColumn(title = "K<sub>2</sub>O(10<sup>-2</sup>)")
    private Double k2O;
    @GeneratorColumn(title = "P<sub>2</sub>O<sub>5</sub>(10<sup>-2</sup>)")
    private Double p2O5;
    @GeneratorColumn(title = "总量(10<sup>-2</sup>)")
    private Double total;
    @GeneratorColumn(title = "其他(10<sup>-2</sup>)")
    private Double others;

    public EpmaData() {
    }


    public EpmaData(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public EpmaData(int id, int sampleId, String mineralName, Double siO2, Double tiO2, Double al2O3, Double cr2O3, Double fe2O3, Double feO, Double niO, Double mnO, Double mgO, Double caO, Double na2O, Double k2O, Double p2O5, Double total, Double others) {
        this.id = id;
        this.sampleId = sampleId;
        this.mineralName = mineralName;
        this.siO2 = siO2;
        this.tiO2 = tiO2;
        this.al2O3 = al2O3;
        this.cr2O3 = cr2O3;
        this.fe2O3 = fe2O3;
        this.feO = feO;
        this.niO = niO;
        this.mnO = mnO;
        this.mgO = mgO;
        this.caO = caO;
        this.na2O = na2O;
        this.k2O = k2O;
        this.p2O5 = p2O5;
        this.total = total;
        this.others = others;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }

    @Column(name="mineral_name", length=20)
    public String getMineralName() {
        return this.mineralName;
    }
    
    public void setMineralName(String mineralName) {
        this.mineralName = mineralName;
    }
    
    @Column(name="si_o2", precision=17, scale=17)
    public Double getSiO2() {
        return this.siO2;
    }
    
    public void setSiO2(Double siO2) {
        this.siO2 = siO2;
    }
    
    @Column(name="ti_o2", precision=17, scale=17)
    public Double getTiO2() {
        return this.tiO2;
    }
    
    public void setTiO2(Double tiO2) {
        this.tiO2 = tiO2;
    }
    
    @Column(name="al2_o3", precision=17, scale=17)
    public Double getAl2O3() {
        return this.al2O3;
    }
    
    public void setAl2O3(Double al2O3) {
        this.al2O3 = al2O3;
    }
    
    @Column(name="cr2_o3", precision=17, scale=17)
    public Double getCr2O3() {
        return this.cr2O3;
    }
    
    public void setCr2O3(Double cr2O3) {
        this.cr2O3 = cr2O3;
    }
    
    @Column(name="fe2_o3", precision=17, scale=17)
    public Double getFe2O3() {
        return this.fe2O3;
    }
    
    public void setFe2O3(Double fe2O3) {
        this.fe2O3 = fe2O3;
    }
    
    @Column(name="fe_o", precision=17, scale=17)
    public Double getFeO() {
        return this.feO;
    }
    
    public void setFeO(Double feO) {
        this.feO = feO;
    }
    
    @Column(name="ni_o", precision=17, scale=17)
    public Double getNiO() {
        return this.niO;
    }
    
    public void setNiO(Double niO) {
        this.niO = niO;
    }
    
    @Column(name="mn_o", precision=17, scale=17)
    public Double getMnO() {
        return this.mnO;
    }
    
    public void setMnO(Double mnO) {
        this.mnO = mnO;
    }
    
    @Column(name="mg_o", precision=17, scale=17)
    public Double getMgO() {
        return this.mgO;
    }
    
    public void setMgO(Double mgO) {
        this.mgO = mgO;
    }
    
    @Column(name="ca_o", precision=17, scale=17)
    public Double getCaO() {
        return this.caO;
    }
    
    public void setCaO(Double caO) {
        this.caO = caO;
    }
    
    @Column(name="na2_o", precision=17, scale=17)
    public Double getNa2O() {
        return this.na2O;
    }
    
    public void setNa2O(Double na2O) {
        this.na2O = na2O;
    }
    
    @Column(name="k2_o", precision=17, scale=17)
    public Double getK2O() {
        return this.k2O;
    }
    
    public void setK2O(Double k2O) {
        this.k2O = k2O;
    }
    
    @Column(name="p2_o5", precision=17, scale=17)
    public Double getP2O5() {
        return this.p2O5;
    }
    
    public void setP2O5(Double p2O5) {
        this.p2O5 = p2O5;
    }
    
    @Column(name="total", precision=17, scale=17)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    
    @Column(name="others", precision=17, scale=17)
    public Double getOthers() {
        return this.others;
    }
    
    public void setOthers(Double others) {
        this.others = others;
    }




}


