package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * REElement generated by hbm2java
 */
@Entity
@Table(name="r_e_element"
    ,schema="public"
)
public class REElement  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private Integer sampleId;
    @GeneratorColumn(title = "镧(10<sup>-6</sup>)")
    private double la;
    @GeneratorColumn(title = "铈(10<sup>-6</sup>)")
    private double ce;
    @GeneratorColumn(title = "镨(10<sup>-6</sup>)")
    private double pr;
    @GeneratorColumn(title = "钕(10<sup>-6</sup>)")
    private double nd;
    @GeneratorColumn(title = "钐(10<sup>-6</sup>)")
    private double sm;
    @GeneratorColumn(title = "铕(10<sup>-6</sup>)")
    private double eu;
    @GeneratorColumn(title = "钆(10<sup>-6</sup>)")
    private double gd;
    @GeneratorColumn(title = "铽(10<sup>-6</sup>)")
    private double tb;
    @GeneratorColumn(title = "镝(10<sup>-6</sup>)")
    private double dy;
    @GeneratorColumn(title = "钬(10<sup>-6</sup>)")
    private double ho;
    @GeneratorColumn(title = "铒(10<sup>-6</sup>)")
    private double er;
    @GeneratorColumn(title = "铥(10<sup>-6</sup>)")
    private double tm;
    @GeneratorColumn(title = "镱(10<sup>-6</sup>)")
    private double yb;
    @GeneratorColumn(title = "镥(10<sup>-6</sup>)")
    private double lu;
    @GeneratorColumn(title = "钇(10<sup>-6</sup>)")
    private double y;
    @GeneratorColumn(title = "钪(10<sup>-6</sup>)")
    private double sc;
    @GeneratorColumn(title = "稀土总量(10<sup>-6</sup>)")
    private double totalReElement;
    @GeneratorColumn(title = "数据形式")
    private String dataType;  //元素   氧化物
    @GeneratorColumn(title = "备注")
    private String remark;

    public REElement() {
    }


    public REElement(int id, double la, double ce, double pr, double nd, double sm, double eu, double gd, double tb, double dy, double ho, double er, double tm, double yb, double lu, double y, double sc, double totalReElement, String dataType) {
        this.id = id;
        this.la = la;
        this.ce = ce;
        this.pr = pr;
        this.nd = nd;
        this.sm = sm;
        this.eu = eu;
        this.gd = gd;
        this.tb = tb;
        this.dy = dy;
        this.ho = ho;
        this.er = er;
        this.tm = tm;
        this.yb = yb;
        this.lu = lu;
        this.y = y;
        this.sc = sc;
        this.totalReElement = totalReElement;
        this.dataType = dataType;
    }
    public REElement(int id, double la, double ce, double pr, double nd, double sm, double eu, double gd, double tb, double dy, double ho, double er, double tm, double yb, double lu, double y, double sc, double totalReElement, String dataType, String remark, Integer sampleId) {
        this.id = id;
        this.la = la;
        this.ce = ce;
        this.pr = pr;
        this.nd = nd;
        this.sm = sm;
        this.eu = eu;
        this.gd = gd;
        this.tb = tb;
        this.dy = dy;
        this.ho = ho;
        this.er = er;
        this.tm = tm;
        this.yb = yb;
        this.lu = lu;
        this.y = y;
        this.sc = sc;
        this.totalReElement = totalReElement;
        this.dataType = dataType;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }
    
    @Column(name="la", nullable=false, precision=17, scale=17)
    public double getLa() {
        return this.la;
    }
    
    public void setLa(double la) {
        this.la = la;
    }
    
    @Column(name="ce", nullable=false, precision=17, scale=17)
    public double getCe() {
        return this.ce;
    }
    
    public void setCe(double ce) {
        this.ce = ce;
    }
    
    @Column(name="pr", nullable=false, precision=17, scale=17)
    public double getPr() {
        return this.pr;
    }
    
    public void setPr(double pr) {
        this.pr = pr;
    }
    
    @Column(name="nd", nullable=false, precision=17, scale=17)
    public double getNd() {
        return this.nd;
    }
    
    public void setNd(double nd) {
        this.nd = nd;
    }
    
    @Column(name="sm", nullable=false, precision=17, scale=17)
    public double getSm() {
        return this.sm;
    }
    
    public void setSm(double sm) {
        this.sm = sm;
    }
    
    @Column(name="eu", nullable=false, precision=17, scale=17)
    public double getEu() {
        return this.eu;
    }
    
    public void setEu(double eu) {
        this.eu = eu;
    }
    
    @Column(name="gd", nullable=false, precision=17, scale=17)
    public double getGd() {
        return this.gd;
    }
    
    public void setGd(double gd) {
        this.gd = gd;
    }
    
    @Column(name="tb", nullable=false, precision=17, scale=17)
    public double getTb() {
        return this.tb;
    }
    
    public void setTb(double tb) {
        this.tb = tb;
    }
    
    @Column(name="dy", nullable=false, precision=17, scale=17)
    public double getDy() {
        return this.dy;
    }
    
    public void setDy(double dy) {
        this.dy = dy;
    }
    
    @Column(name="ho", nullable=false, precision=17, scale=17)
    public double getHo() {
        return this.ho;
    }
    
    public void setHo(double ho) {
        this.ho = ho;
    }
    
    @Column(name="er", nullable=false, precision=17, scale=17)
    public double getEr() {
        return this.er;
    }
    
    public void setEr(double er) {
        this.er = er;
    }
    
    @Column(name="tm", nullable=false, precision=17, scale=17)
    public double getTm() {
        return this.tm;
    }
    
    public void setTm(double tm) {
        this.tm = tm;
    }
    
    @Column(name="yb", nullable=false, precision=17, scale=17)
    public double getYb() {
        return this.yb;
    }
    
    public void setYb(double yb) {
        this.yb = yb;
    }
    
    @Column(name="lu", nullable=false, precision=17, scale=17)
    public double getLu() {
        return this.lu;
    }
    
    public void setLu(double lu) {
        this.lu = lu;
    }
    
    @Column(name="y", nullable=false, precision=17, scale=17)
    public double getY() {
        return this.y;
    }
    
    public void setY(double y) {
        this.y = y;
    }
    
    @Column(name="sc", nullable=false, precision=17, scale=17)
    public double getSc() {
        return this.sc;
    }
    
    public void setSc(double sc) {
        this.sc = sc;
    }
    
    @Column(name="total_re_element", nullable=false, precision=17, scale=17)
    public double getTotalReElement() {
        return this.totalReElement;
    }
    
    public void setTotalReElement(double totalReElement) {
        this.totalReElement = totalReElement;
    }
    
    @Column(name="data_type", nullable=false, length=10)
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    
    @Column(name="remark", length=50)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


