package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * RockSectionIdentify generated by hbm2java
 */
@Entity
@Table(name="rock_section_identify"
    ,schema="public"
)
public class RockSectionIdentify  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private Integer sampleId;
    @GeneratorColumn(title = "野外名称")
    private String fieldRockName;
    @GeneratorColumn(title = "镜下描述")
    private String microScopicDescribe;
    @GeneratorColumn(title = "鉴定名称")
    private String authorizedRockName;
    @GeneratorColumn(title = "镜下照片")
    private String microscopicPhoto;
    @GeneratorColumn(title = "备注")
    private String remark;

    public RockSectionIdentify() {
    }


    public RockSectionIdentify(int id, String fieldRockName, String microScopicDescribe, String authorizedRockName, String microscopicPhoto) {
        this.id = id;
        this.fieldRockName = fieldRockName;
        this.microScopicDescribe = microScopicDescribe;
        this.authorizedRockName = authorizedRockName;
        this.microscopicPhoto = microscopicPhoto;
    }
    public RockSectionIdentify(int id, String fieldRockName, String microScopicDescribe, String authorizedRockName, String microscopicPhoto, String remark, Integer sampleId) {
        this.id = id;
        this.fieldRockName = fieldRockName;
        this.microScopicDescribe = microScopicDescribe;
        this.authorizedRockName = authorizedRockName;
        this.microscopicPhoto = microscopicPhoto;
        this.remark = remark;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id")
    public Integer getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }
    
    @Column(name="field_rock_name", nullable=false, length=15)
    public String getFieldRockName() {
        return this.fieldRockName;
    }
    
    public void setFieldRockName(String fieldRockName) {
        this.fieldRockName = fieldRockName;
    }
    
    @Column(name="microScopic_describe", nullable=false, length=500)
    public String getMicroScopicDescribe() {
        return this.microScopicDescribe;
    }
    
    public void setMicroScopicDescribe(String microScopicDescribe) {
        this.microScopicDescribe = microScopicDescribe;
    }
    
    @Column(name="authorized_rock_name", nullable=false, length=50)
    public String getAuthorizedRockName() {
        return this.authorizedRockName;
    }
    
    public void setAuthorizedRockName(String authorizedRockName) {
        this.authorizedRockName = authorizedRockName;
    }
    
    @Column(name="microscopic_photo", nullable=false, length=100)
    public String getMicroscopicPhoto() {
        return this.microscopicPhoto;
    }
    
    public void setMicroscopicPhoto(String microscopicPhoto) {
        this.microscopicPhoto = microscopicPhoto;
    }
    
    @Column(name="remark", length=50)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


