package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * SampleBasicInfo generated by hbm2java
 */
@Entity
@Table(name="sample_basic_info"
    ,schema="public"
)
public class SampleBasicInfo  implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品编码", condition = true,order=true)
    private String sampleId;
    @GeneratorColumn(title = "原始样品编码", condition = true,order=true)
    private String originalSampleId;
    @GeneratorColumn(title = "地理经度",order = true)
    private Double longitude;
    @GeneratorColumn(title = "地理纬度",order = true)
    private Double latitude;
    @GeneratorColumn(title = "国家编码",condition = true,order = true)
    private String countryCode;
    @GeneratorColumn(title = "所在地区",condition = true,like=true,order = true)
    private String location;
    @GeneratorColumn(title = "岩性",condition=true,order=true)
    private String lithology;
    @GeneratorColumn(title = "岩石名称",condition=true,order=true)
    private String rockName;
    @GeneratorColumn(title = "岩石名称代码",condition = true,order = true)
    private String rockCode;
    @GeneratorColumn(title = "地质年代",condition=true,order=true)
    private String era;
    @GeneratorColumn(title = "地质体名称",condition=true,order=true)
    private String geobodyName;
    @GeneratorColumn(title = "地质体代码",condition=true,order=true)
    private String geobodyCode;

    @GeneratorColumn(title = "构造位置",condition = true,order = true,like = true)
    private String tectonicLocation;
    @GeneratorColumn(title = "一级构造单元",condition = true,order = true,like = true)
    private String primaryStructuralUnit;
    @GeneratorColumn(title = "二级构造单元",condition = true,order = true,like = true)
    private String secondaryStructuralUnit;
    @GeneratorColumn(title = "三级构造单元",condition = true,order = true,like = true)
    private String tertiarySturcturalUnit;
    @GeneratorColumn(title = "围岩时代",condition = true,order = true,like = true)
    private String surroundingRockAge;
    @GeneratorColumn(title = "围岩岩性",condition = true,order = true,like = true)
    private String surroundingRockLithology;
    @GeneratorColumn(title = "与围岩关系",condition = true,order = true,like = true)
    private String relationshipWithSurroundingRock;
    @GeneratorColumn(title = "形态",condition = true,order = true,like = true)
    private String form;
    @GeneratorColumn(title = "是否切割区域构造线",condition = true,order = true)
    private Boolean isCutAreaConstructionLine;
    @GeneratorColumn(title = "变形程度",condition = true,order = true,like = true)
    private String degreeOfDeformation;
    @GeneratorColumn(title = "特征矿物",condition = true,order = true,like = true)
    private String characteristicMinerals;
    @GeneratorColumn(title = "成因类型",condition = true,order = true,like = true)
    private String geneticType;

    @GeneratorColumn(title = "构造类型",condition = true,order = true,like = true)
    private String tectonicType;
    @GeneratorColumn(title = "构造类型判别来源",condition = true,order = true,like = true)
    private String sourceOfStructuralTypeDiscrimination;
    @GeneratorColumn(title = "碱性程度",condition = true,order = true,like = true)
    private String alkalinity;
    @GeneratorColumn(title = "铝质程度",condition = true,order = true,like = true)
    private String aluminumQuality;

    @GeneratorColumn(title = "年龄",order = true)
    private Double age;
    @GeneratorColumn(title = "年龄误差",order = true)
    private Double ageError;

    @GeneratorColumn(title = "样品照片",order = true)
    private String photo;
    @GeneratorColumn(title = "样品采集人员",condition=true,order=true,like=true)
    private String collector;
    @GeneratorColumn(title = "采集人员单位",condition=true,order=true,like=true)
    private String collectorOrg;
    @GeneratorColumn(title = "样品审核人",condition=true,order=true,like=true)
    private String reviewer;
    @GeneratorColumn(title = "分析/鉴定单位",condition=true,order=true,like=true)
    private String analyzeOrg;
    @GeneratorColumn(title = "分析/鉴定人员",condition=true,order=true,like=true)
    private String analyzePerson;

    @GeneratorColumn(title = "测试对象",condition = true,order = true,like = true)
    private String testObject;

    @GeneratorColumn(title = "分析/测定时间",condition=true,order=true,like=true)
    private String testDate;
    @GeneratorColumn(title = "分析/测定方法",condition=true,order=true,like=true)
    private String testMethod;
    @GeneratorColumn(title = "选用年龄",order = true)
    private Double ageSelected;
    @GeneratorColumn(title = "选用年龄误差",order = true)
    private Double ageSelectedError;


    @GeneratorColumn(title = "发表文献编号",order = true)
    private Integer articleId;

    @GeneratorColumn(title = "文章DOI",condition = true,order = true,like = true)
    private String articleDoi;
    @GeneratorColumn(title = "审核",condition = true,order = true)
    private Boolean hasChecked;
    @GeneratorColumn(title = "备注")
    private String remark;

    public SampleBasicInfo() {
    }


    public SampleBasicInfo(Integer id, String originalSampleId, Double longitude, Double latitude) {
        this.id = id;
        this.originalSampleId = originalSampleId;
        this.longitude = longitude;
        this.latitude = latitude;
    }
    public SampleBasicInfo(Integer id, String sampleId, String originalSampleId, Double longitude, Double latitude, String countryCode, String location, String lithology, String rockName, String rockCode, String era, String geobodyName, String geobodyCode, String photo, String collector, String collectorOrg, String reviewer, String remark, String analyzeOrg, String testDate, String testMethod, String analyzePerson, Integer articleId, String tectonicLocation, String primaryStructuralUnit, String secondaryStructuralUnit, String tertiarySturcturalUnit, String surroundingRockAge, String surroundingRockLithology, String relationshipWithSurroundingRock, String form, Boolean isCutAreaConstructionLine, String degreeOfDeformation, String characteristicMinerals, String geneticType, Double age, Double ageError, String testObject, Double ageSelected, Double ageSelectedError, String tectonicType, String sourceOfStructuralTypeDiscrimination, String alkalinity, String aluminumQuality, String articleDoi, Boolean hasChecked) {
        this.id = id;
        this.sampleId = sampleId;
        this.originalSampleId = originalSampleId;
        this.longitude = longitude;
        this.latitude = latitude;
        this.countryCode = countryCode;
        this.location = location;
        this.lithology = lithology;
        this.rockName = rockName;
        this.rockCode = rockCode;
        this.era = era;
        this.geobodyName = geobodyName;
        this.geobodyCode = geobodyCode;
        this.photo = photo;
        this.collector = collector;
        this.collectorOrg = collectorOrg;
        this.reviewer = reviewer;
        this.remark = remark;
        this.analyzeOrg = analyzeOrg;
        this.testDate = testDate;
        this.testMethod = testMethod;
        this.analyzePerson = analyzePerson;
        this.articleId = articleId;
        this.tectonicLocation = tectonicLocation;
        this.primaryStructuralUnit = primaryStructuralUnit;
        this.secondaryStructuralUnit = secondaryStructuralUnit;
        this.tertiarySturcturalUnit = tertiarySturcturalUnit;
        this.surroundingRockAge = surroundingRockAge;
        this.surroundingRockLithology = surroundingRockLithology;
        this.relationshipWithSurroundingRock = relationshipWithSurroundingRock;
        this.form = form;
        this.isCutAreaConstructionLine = isCutAreaConstructionLine;
        this.degreeOfDeformation = degreeOfDeformation;
        this.characteristicMinerals = characteristicMinerals;
        this.geneticType = geneticType;
        this.age = age;
        this.ageError = ageError;
        this.testObject = testObject;
        this.ageSelected = ageSelected;
        this.ageSelectedError = ageSelectedError;
        this.tectonicType = tectonicType;
        this.sourceOfStructuralTypeDiscrimination = sourceOfStructuralTypeDiscrimination;
        this.alkalinity = alkalinity;
        this.aluminumQuality = aluminumQuality;
        this.articleDoi = articleDoi;
        this.hasChecked = hasChecked;
    }

    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id", length=12)
    public String getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    @Column(name="original_sample_id", nullable=false, length=12)
    public String getOriginalSampleId() {
        return this.originalSampleId;
    }

    public void setOriginalSampleId(String originalSampleId) {
        this.originalSampleId = originalSampleId;
    }

    @Column(name="longitude", nullable=false, precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @Column(name="latitude", nullable=false, precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    @Column(name="country_code", length=2)
    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    @Column(name="location", length=20)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name="lithology", length=20)
    public String getLithology() {
        return this.lithology;
    }

    public void setLithology(String lithology) {
        this.lithology = lithology;
    }

    @Column(name="rock_name", length=50)
    public String getRockName() {
        return this.rockName;
    }

    public void setRockName(String rockName) {
        this.rockName = rockName;
    }

    @Column(name="rock_code", length=30)
    public String getRockCode() {
        return this.rockCode;
    }

    public void setRockCode(String rockCode) {
        this.rockCode = rockCode;
    }

    @Column(name="era", length=30)
    public String getEra() {
        return this.era;
    }

    public void setEra(String era) {
        this.era = era;
    }

    @Column(name="geobody_name", length=50)
    public String getGeobodyName() {
        return this.geobodyName;
    }

    public void setGeobodyName(String geobodyName) {
        this.geobodyName = geobodyName;
    }

    @Column(name="geobody_code", length=30)
    public String getGeobodyCode() {
        return this.geobodyCode;
    }

    public void setGeobodyCode(String geobodyCode) {
        this.geobodyCode = geobodyCode;
    }

    @Column(name="photo", length=30)
    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Column(name="collector", length=30)
    public String getCollector() {
        return this.collector;
    }

    public void setCollector(String collector) {
        this.collector = collector;
    }

    @Column(name="collector_org", length=30)
    public String getCollectorOrg() {
        return this.collectorOrg;
    }

    public void setCollectorOrg(String collectorOrg) {
        this.collectorOrg = collectorOrg;
    }

    @Column(name="reviewer", length=30)
    public String getReviewer() {
        return this.reviewer;
    }

    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }

    @Column(name="remark", length=50)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="analyze_org", length=40)
    public String getAnalyzeOrg() {
        return this.analyzeOrg;
    }

    public void setAnalyzeOrg(String analyzeOrg) {
        this.analyzeOrg = analyzeOrg;
    }

    @Column(name="test_date", length=10)
    public String getTestDate() {
        return this.testDate;
    }

    public void setTestDate(String testDate) {
        this.testDate = testDate;
    }

    @Column(name="test_method", length=20)
    public String getTestMethod() {
        return this.testMethod;
    }

    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod;
    }

    @Column(name="analyze_person", length=30)
    public String getAnalyzePerson() {
        return this.analyzePerson;
    }

    public void setAnalyzePerson(String analyzePerson) {
        this.analyzePerson = analyzePerson;
    }

    @Column(name="article_id")
    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    @Column(name="tectonic_location", length=100)
    public String getTectonicLocation() {
        return this.tectonicLocation;
    }

    public void setTectonicLocation(String tectonicLocation) {
        this.tectonicLocation = tectonicLocation;
    }

    @Column(name="primary_structural_unit", length=100)
    public String getPrimaryStructuralUnit() {
        return this.primaryStructuralUnit;
    }

    public void setPrimaryStructuralUnit(String primaryStructuralUnit) {
        this.primaryStructuralUnit = primaryStructuralUnit;
    }

    @Column(name="secondary_structural_unit", length=100)
    public String getSecondaryStructuralUnit() {
        return this.secondaryStructuralUnit;
    }

    public void setSecondaryStructuralUnit(String secondaryStructuralUnit) {
        this.secondaryStructuralUnit = secondaryStructuralUnit;
    }

    @Column(name="tertiary_sturctural_unit", length=100)
    public String getTertiarySturcturalUnit() {
        return this.tertiarySturcturalUnit;
    }

    public void setTertiarySturcturalUnit(String tertiarySturcturalUnit) {
        this.tertiarySturcturalUnit = tertiarySturcturalUnit;
    }

    @Column(name="surrounding_rock_age", length=50)
    public String getSurroundingRockAge() {
        return this.surroundingRockAge;
    }

    public void setSurroundingRockAge(String surroundingRockAge) {
        this.surroundingRockAge = surroundingRockAge;
    }

    @Column(name="surrounding_rock_lithology", length=50)
    public String getSurroundingRockLithology() {
        return this.surroundingRockLithology;
    }

    public void setSurroundingRockLithology(String surroundingRockLithology) {
        this.surroundingRockLithology = surroundingRockLithology;
    }

    @Column(name="relationship_with_surrounding_rock", length=50)
    public String getRelationshipWithSurroundingRock() {
        return this.relationshipWithSurroundingRock;
    }

    public void setRelationshipWithSurroundingRock(String relationshipWithSurroundingRock) {
        this.relationshipWithSurroundingRock = relationshipWithSurroundingRock;
    }

    @Column(name="form", length=50)
    public String getForm() {
        return this.form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    @Column(name="is_cut_area_construction_line")
    public Boolean getIsCutAreaConstructionLine() {
        return this.isCutAreaConstructionLine;
    }

    public void setIsCutAreaConstructionLine(Boolean isCutAreaConstructionLine) {
        this.isCutAreaConstructionLine = isCutAreaConstructionLine;
    }

    @Column(name="degree_of_deformation", length=50)
    public String getDegreeOfDeformation() {
        return this.degreeOfDeformation;
    }

    public void setDegreeOfDeformation(String degreeOfDeformation) {
        this.degreeOfDeformation = degreeOfDeformation;
    }

    @Column(name="characteristic_minerals", length=50)
    public String getCharacteristicMinerals() {
        return this.characteristicMinerals;
    }

    public void setCharacteristicMinerals(String characteristicMinerals) {
        this.characteristicMinerals = characteristicMinerals;
    }

    @Column(name="genetic_type", length=50)
    public String getGeneticType() {
        return this.geneticType;
    }

    public void setGeneticType(String geneticType) {
        this.geneticType = geneticType;
    }

    @Column(name="age", precision=17, scale=17)
    public Double getAge() {
        return this.age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }

    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }

    @Column(name="test_object", length=50)
    public String getTestObject() {
        return this.testObject;
    }

    public void setTestObject(String testObject) {
        this.testObject = testObject;
    }

    @Column(name="age_selected", precision=17, scale=17)
    public Double getAgeSelected() {
        return this.ageSelected;
    }

    public void setAgeSelected(Double ageSelected) {
        this.ageSelected = ageSelected;
    }

    @Column(name="age_selected_error", precision=17, scale=17)
    public Double getAgeSelectedError() {
        return this.ageSelectedError;
    }

    public void setAgeSelectedError(Double ageSelectedError) {
        this.ageSelectedError = ageSelectedError;
    }

    @Column(name="tectonic_type", length=50)
    public String getTectonicType() {
        return this.tectonicType;
    }

    public void setTectonicType(String tectonicType) {
        this.tectonicType = tectonicType;
    }

    @Column(name="source_of_structural_type_discrimination", length=50)
    public String getSourceOfStructuralTypeDiscrimination() {
        return this.sourceOfStructuralTypeDiscrimination;
    }

    public void setSourceOfStructuralTypeDiscrimination(String sourceOfStructuralTypeDiscrimination) {
        this.sourceOfStructuralTypeDiscrimination = sourceOfStructuralTypeDiscrimination;
    }

    @Column(name="alkalinity", length=50)
    public String getAlkalinity() {
        return this.alkalinity;
    }

    public void setAlkalinity(String alkalinity) {
        this.alkalinity = alkalinity;
    }

    @Column(name="aluminum_quality", length=50)
    public String getAluminumQuality() {
        return this.aluminumQuality;
    }

    public void setAluminumQuality(String aluminumQuality) {
        this.aluminumQuality = aluminumQuality;
    }

    @Column(name="article_doi", length=100)
    public String getArticleDoi() {
        return this.articleDoi;
    }

    public void setArticleDoi(String articleDoi) {
        this.articleDoi = articleDoi;
    }

    @Column(name="has_checked")
    public Boolean getHasChecked() {
        return this.hasChecked;
    }

    public void setHasChecked(Boolean hasChecked) {
        this.hasChecked = hasChecked;
    }




}