package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * StableIsotopeAnalyse generated by hbm2java
 */
@Entity
@Table(name="stable_isotope_analyse"
    ,schema="public"
)
public class StableIsotopeAnalyse  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "分析项目")
    private String analyzeItem;
    @GeneratorColumn(title = "分析值")
    private Double analyzeValue;
   // @GeneratorColumn(title = "备注")
   // private String remark;
    public StableIsotopeAnalyse() {
    }


    public StableIsotopeAnalyse(int id, int sampleId) {
        this.id = id;
        this.sampleId = sampleId;
    }
    public StableIsotopeAnalyse(int id, String analyzeItem, int sampleId, Double analyzeValue) {
        this.id = id;
        this.analyzeItem = analyzeItem;
        this.sampleId = sampleId;
        this.analyzeValue = analyzeValue;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }
    
    @Column(name="analyze_item", length=12)
    public String getAnalyzeItem() {
        return this.analyzeItem;
    }
    
    public void setAnalyzeItem(String analyzeItem) {
        this.analyzeItem = analyzeItem;
    }
    
    @Column(name="analyze_value", precision=17, scale=17)
    public Double getAnalyzeValue() {
        return this.analyzeValue;
    }
    
    public void setAnalyzeValue(Double analyzeValue) {
        this.analyzeValue = analyzeValue;
    }

    /*
    @Column(name="remark", length=50)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
*/


}


