package cn.ac.cags.entities.rock;
// Generated 2020-2-15 13:24:38 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * TraceElementData generated by hbm2java
 */
@Entity
@Table(name="trace_element_data"
    ,schema="public"
)
public class TraceElementData  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private Integer id;
    @GeneratorColumn(title = "样品",condition = true,order = true)
    private int sampleId;
    @GeneratorColumn(title = "分析元素")
    private String analyzeElement;
    @GeneratorColumn(title = "分析数据(10<sup>-6</sup>）")
    private String analyzeData;

    public TraceElementData() {
    }


    public TraceElementData(int id, String analyzeElement, int sampleId) {
        this.id = id;
        this.analyzeElement = analyzeElement;
        this.sampleId = sampleId;
    }
    public TraceElementData(int id, String analyzeElement, String analyzeData, int sampleId) {
        this.id = id;
        this.analyzeElement = analyzeElement;
        this.analyzeData = analyzeData;
        this.sampleId = sampleId;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id", nullable=false)
    public int getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }
    
    @Column(name="analyze_element", nullable=false, length=15)
    public String getAnalyzeElement() {
        return this.analyzeElement;
    }
    
    public void setAnalyzeElement(String analyzeElement) {
        this.analyzeElement = analyzeElement;
    }
    
    @Column(name="analyze_data", length=40)
    public String getAnalyzeData() {
        return this.analyzeData;
    }
    
    public void setAnalyzeData(String analyzeData) {
        this.analyzeData = analyzeData;
    }




}


