package cn.ac.cags.entities.dde;
// Generated 2021-7-29 11:20:18 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * SampleInfo generated by hbm2java
 */
@Entity
@Table(name="sample_info"
        ,schema="public"
)
public class SampleInfo  implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID",order=true)
    private Integer id;
    @GeneratorColumn(title = "Sample Id", condition = true,order=true)
    private String sampleId;
    @GeneratorColumn(title = "Oraginal Sample Id", condition = true,order=true)
    private String oraginalSampleId;
    @GeneratorColumn(title = "Longitude",order = true)
    private Double longitude;
    @GeneratorColumn(title = "Latitude",order = true)
    private Double latitude;
    @GeneratorColumn(title = "Location",condition = true,like=true,order = true)
    private String location;
    @GeneratorColumn(title = "Region Location",condition = true,like=true,order = true)
    private String regionLocation;
    @GeneratorColumn(title = "Location Type",condition = true,like=true,order = true)
    private String locationType;
    @GeneratorColumn(title = "Tectonic Location",condition = true,order = true,like = true)
    private String tectonicLocation;
    @GeneratorColumn(title = "Tectonic Type",condition=true,order=true,like = true)
    private String tectonicType;
    @GeneratorColumn(title = "Lithology",condition=true,order=true,like = true)
    private String lithology;
    @GeneratorColumn(title = "Orginal Lithology",condition=true,order=true,like = true)
    private String lithologyOrigin;
    @GeneratorColumn(title = "Occurrence",condition=true,order=true,like = true)
    private String occurrence;
    @GeneratorColumn(title = "Intrusion",condition=true,order=true,like = true)
    private String intrusion;
    @GeneratorColumn(title = "Pluton",condition=true,order=true,like = true)
    private String pluton;
    @GeneratorColumn(title = "Original Pluton",condition=true,order=true,like = true)
    private String plutonOrigin;
    @GeneratorColumn(title = "Rock Name",condition=true,order=true,like = true)
    private String rockName;
    @GeneratorColumn(title = "Rock Code",condition=true,order=true,like = true)
    private String rockCode;
    @GeneratorColumn(title = "Era",condition=true,order=true,like = true)
    private String era;
    @GeneratorColumn(title = "Geobody Name",condition=true,order=true,like = true)
    private String geobodyName;
    @GeneratorColumn(title = "Geobody Code",condition=true,order=true,like = true)
    private String geobodyCode;
    @GeneratorColumn(title = "Surrounding Rock Age",condition=true,order=true,like = true)
    private String surroundingRockAge;
    @GeneratorColumn(title = "Surrounding Rock Lithology",condition=true,order=true,like = true)
    private String surroundingRockLithology;
    @GeneratorColumn(title = "Relationship with Surrounding Rock",condition=true,order=true,like = true)
    private String relationshipWithSurroundingRock;
    @GeneratorColumn(title = "Form",condition=true,order=true,like = true)
    private String form;
    @GeneratorColumn(title = "Whether to Cut Area Construction Line",condition=true,order=true,like = true)
    private String whetherToCutAreaConstructionLine;
    @GeneratorColumn(title = "Degree of Deformation",condition=true,order=true,like = true)
    private String degreeOfDeformation;
    @GeneratorColumn(title = "Characteristic Minerals",condition=true,order=true,like = true)
    private String characteristicMinerals;
    @GeneratorColumn(title = "Mining Area",condition=true,order=true,like = true)
    private String miningArea;
    @GeneratorColumn(title = "Ore Type",condition=true,order=true,like = true)
    private String oreType;
    @GeneratorColumn(title = "Genetic Type",condition=true,order=true,like = true)
    private String geneticType;
    @GeneratorColumn(title = "Age（Ma）",condition=true,order=true)
    private Double age;
    @GeneratorColumn(title = "Age Error（Ma）",condition=true,order=true)
    private Double ageError;
    @GeneratorColumn(title = "Age Selected（Ma）",condition=true,order=true)
    private Double ageSelected;
    @GeneratorColumn(title = "Age Selected Error（Ma）",condition=true,order=true)
    private Double ageSelectedError;
    @GeneratorColumn(title = "Test Object",condition=true,order=true,like = true)
    private String testObject;
    @GeneratorColumn(title = "Test Method",condition=true,order=true,like = true)
    private String testMethod;
    @GeneratorColumn(title = "Primary Structural Unit",condition = true,order = true,like = true)
    private String primaryStructuralUnit;
    @GeneratorColumn(title = "Secondary Structural Unit",condition = true,order = true,like = true)
    private String secondaryStructuralUnit;
    @GeneratorColumn(title = "Tertiary Structural Unit",condition = true,order = true,like = true)
    private String tertiaryStructuralUnit;
    @GeneratorColumn(title = "Source of Structural Type Discrimination",condition=true,order=true,like = true)
    private String sourceOfStructuralTypeDiscrimination;
    @GeneratorColumn(title = "Alkalinity",condition=true,order=true,like = true)
    private String alkalinity;
    @GeneratorColumn(title = "Aluminum Quality",condition=true,order=true,like = true)
    private String aluminumQuality;
    @GeneratorColumn(title = "Photo",condition=true,order=true,like = true)
    private String photo;
    @GeneratorColumn(title = "Collector",condition=true,order=true,like = true)
    private String collector;
    @GeneratorColumn(title = "Collector Org",condition=true,order=true,like = true)
    private String collectorOrg;
    @GeneratorColumn(title = "Reviewer",condition=true,order=true,like = true)
    private String reviewer;
    @GeneratorColumn(title = "Analyze Org",condition=true,order=true,like = true)
    private String analyzeOrg;
    @GeneratorColumn(title = "Analyze Person",condition=true,order=true,like = true)
    private String analyzePerson;
    @GeneratorColumn(title = "Test Date",condition=true,order=true,like = true)
    private String testDate;
    @GeneratorColumn(title = "Data Source",condition=true,order=true,like = true)
    private String dataSource;
    @GeneratorColumn(title = "Article DOI",condition=true,order=true,like = true)
    private String articleDoi;
    @GeneratorColumn(title = "Remark",condition=true,order=true,like = true)
    private String remark;
    @GeneratorColumn(title = "Ref.Author",condition=true,order=true,like = true)
    private String refAuthor;
    @GeneratorColumn(title = "Ref.Year",condition=true,order=true,like = true)
    private String refYear;
    @GeneratorColumn(title = "Ref.Magazine",condition=true,order=true,like = true)
    private String refMagazine;
    @GeneratorColumn(title = "Issue Page",condition=true,order=true,like = true)
    private String issuePage;
    @GeneratorColumn(title = "Ref.Title",condition=true,order=true,like = true)
    private String refTitle;
    @GeneratorColumn(title = "Ref.Origin",condition=true,order=true,like = true)
    private String refOrigin;
    @GeneratorColumn(title = "Ref.Magazine.Origin",condition=true,order=true,like = true)
    private String refMagazineOrigin;
    @GeneratorColumn(title = "Ref.Title.Origin",condition=true,order=true,like = true)
    private String refTitleOrigin;
    //主量元素
    @GeneratorColumn(title = "S<sub>i</sub>O<sub>2</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double sio2;
    @GeneratorColumn(title = "T<sub>i</sub>O<sub>2</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double tio2;
    @GeneratorColumn(title = "Al<sub>2</sub>O<sub>3</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double al2o3;
    @GeneratorColumn(title = "Fe<sub>2</sub>O<sub>3</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double fe2o3;
    @GeneratorColumn(title = "FeO（10<sup>-2</sup>）",condition=true,order=true)
    private Double feo;
    @GeneratorColumn(title = "Fe<sub>2</sub>O<sub>3</sub>T（10<sup>-2</sup>）",condition=true,order=true)
    private Double fe2o3t;
    @GeneratorColumn(title = "FeOT（10<sup>-2</sup>）",condition=true,order=true)
    private Double feot;
    @GeneratorColumn(title = "TFe（10<sup>-2</sup>）",condition=true,order=true)
    private Double tfe;
    @GeneratorColumn(title = "MnO（10<sup>-2</sup>）",condition=true,order=true)
    private Double mno;
    @GeneratorColumn(title = "MgO（10<sup>-2</sup>）",condition=true,order=true)
    private Double mgo;
    @GeneratorColumn(title = "CaO（10<sup>-2</sup>）",condition=true,order=true)
    private Double cao;
    @GeneratorColumn(title = "Na<sub>2</sub>O（10<sup>-2</sup>）",condition=true,order=true)
    private Double na2o;
    @GeneratorColumn(title = "K<sub>2</sub>O（10<sup>-2</sup>）",condition=true,order=true)
    private Double k2o;
    @GeneratorColumn(title = "P<sub>2</sub>O<sub>5</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double p2o5;
    @GeneratorColumn(title = "H<sub>2</sub>O<sup>+</sup>（10<sup>-2</sup>）",condition=true,order=true)
    private Double h2op;
    @GeneratorColumn(title = "H<sub>2</sub>O<sup>-</sup>（10<sup>-2</sup>）",condition=true,order=true)
    private Double h2on;
    @GeneratorColumn(title = "CO<sub>2</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double co2;
    @GeneratorColumn(title = "SO<sub>3</sub>（10<sup>-2</sup>）",condition=true,order=true)
    private Double so3;
    @GeneratorColumn(title = "F（10<sup>-2</sup>）",condition=true,order=true)
    private Double f;
    @GeneratorColumn(title = "Cl（10<sup>-2</sup>）",condition=true,order=true)
    private Double cl;
    @GeneratorColumn(title = "LOI（10<sup>-2</sup>）",condition=true,order=true)
    private Double loi;
    @GeneratorColumn(title = "Total（10<sup>-2</sup>）",condition=true,order=true)
    private Double total;
    //上面是常量/主量元素，下面是稀土元素
    @GeneratorColumn(title = "镧 La（10<sup>-6</sup>）",condition=true,order=true)
    private Double la;
    @GeneratorColumn(title = "铈 Ce（10<sup>-6</sup>）",condition=true,order=true)
    private Double ce;
    @GeneratorColumn(title = "镨 Pr（10<sup>-6</sup>）",condition=true,order=true)
    private Double pr;
    @GeneratorColumn(title = "钕 Nd（10<sup>-6</sup>）",condition=true,order=true)
    private Double nd;
    @GeneratorColumn(title = "钷 Pm（10<sup>-6</sup>）",condition=true,order=true)
    private Double pm;
    @GeneratorColumn(title = "钐 Sm（10<sup>-6</sup>）",condition=true,order=true)
    private Double sm;
    @GeneratorColumn(title = "铕 Eu（10<sup>-6</sup>）",condition=true,order=true)
    private Double eu;
    @GeneratorColumn(title = "钆 Gd（10<sup>-6</sup>）",condition=true,order=true)
    private Double gd;
    @GeneratorColumn(title = "铽 Tb（10<sup>-6</sup>）",condition=true,order=true)
    private Double tb;
    @GeneratorColumn(title = "镝 Dy（10<sup>-6</sup>）",condition=true,order=true)
    private Double dy;
    @GeneratorColumn(title = "钬 Ho（10<sup>-6</sup>）",condition=true,order=true)
    private Double ho;
    @GeneratorColumn(title = "铒 Er（10<sup>-6</sup>）",condition=true,order=true)
    private Double er;
    @GeneratorColumn(title = "铥 Tm（10<sup>-6</sup>）",condition=true,order=true)
    private Double tm;
    @GeneratorColumn(title = "镱 Yb（10<sup>-6</sup>）",condition=true,order=true)
    private Double yb;
    @GeneratorColumn(title = "镥 Lu（10<sup>-6</sup>）",condition=true,order=true)
    private Double lu;
    @GeneratorColumn(title = "钇 Y（10<sup>-6</sup>）",condition=true,order=true)
    private Double y;
    @GeneratorColumn(title = "钪 Sc（10<sup>-6</sup>）",condition=true,order=true)
    private Double sc;
    @GeneratorColumn(title = "Total Re Element（10<sup>-6</sup>）",condition=true,order=true)
    private Double totalReElement;
    //上面是稀土，下面是微量元素
    @GeneratorColumn(title = "钒 V（10<sup>-6</sup>）",condition=true,order=true)
    private Double v;
    @GeneratorColumn(title = "铬 Cr（10<sup>-6</sup>）",condition=true,order=true)
    private Double cr;
    @GeneratorColumn(title = "钴 Co（10<sup>-6</sup>）",condition=true,order=true)
    private Double co;
    @GeneratorColumn(title = "镍 Ni（10<sup>-6</sup>）",condition=true,order=true)
    private Double ni;
    @GeneratorColumn(title = "锰 Mn（10<sup>-6</sup>）",condition=true,order=true)
    private Double mn;
    @GeneratorColumn(title = "铜 Cu（10<sup>-6</sup>）",condition=true,order=true)
    private Double cu;
    @GeneratorColumn(title = "锌 Zn（10<sup>-6</sup>）",condition=true,order=true)
    private Double zn;
    @GeneratorColumn(title = "镓 Ga（10<sup>-6</sup>）",condition=true,order=true)
    private Double ga;
    @GeneratorColumn(title = "锗 Ge（10<sup>-6</sup>）",condition=true,order=true)
    private Double ge;
    @GeneratorColumn(title = "铯 Cs（10<sup>-6</sup>）",condition=true,order=true)
    private Double cs;
    @GeneratorColumn(title = "铷 Rb（10<sup>-6</sup>）",condition=true,order=true)
    private Double rb;
    @GeneratorColumn(title = "钡 Ba（10<sup>-6</sup>）",condition=true,order=true)
    private Double ba;
    @GeneratorColumn(title = "钍 Th（10<sup>-6</sup>）",condition=true,order=true)
    private Double th;
    @GeneratorColumn(title = "铀 U（10<sup>-6</sup>）",condition=true,order=true)
    private Double u;
    @GeneratorColumn(title = "铌 Nb（10<sup>-6</sup>）",condition=true,order=true)
    private Double nb;
    @GeneratorColumn(title = "钽 Ta（10<sup>-6</sup>）",condition=true,order=true)
    private Double ta;
    @GeneratorColumn(title = "钛 Ti（10<sup>-6</sup>）",condition=true,order=true)
    private Double ti;
    @GeneratorColumn(title = "磷 P（10<sup>-6</sup>）",condition=true,order=true)
    private Double p;
    @GeneratorColumn(title = "铅 Pb（10<sup>-6</sup>）",condition=true,order=true)
    private Double pb;
    @GeneratorColumn(title = "锶 Sr（10<sup>-6</sup>）",condition=true,order=true)
    private Double sr;
    @GeneratorColumn(title = "锆 Zr（10<sup>-6</sup>）",condition=true,order=true)
    private Double zr;
    @GeneratorColumn(title = "铪 Hf（10<sup>-6</sup>）",condition=true,order=true)
    private Double hf;
    @GeneratorColumn(title = "锂 Li（10<sup>-6</sup>）",condition=true,order=true)
    private Double li;
    @GeneratorColumn(title = "铍 Be（10<sup>-6</sup>）",condition=true,order=true)
    private Double be;
    @GeneratorColumn(title = "钨 W（10<sup>-6</sup>）",condition=true,order=true)
    private Double w;
    @GeneratorColumn(title = "铂 Pt（10<sup>-6</sup>）",condition=true,order=true)
    private Double pt;
    @GeneratorColumn(title = "钯 Pd（10<sup>-6</sup>）",condition=true,order=true)
    private Double pd;
    @GeneratorColumn(title = "锇 Os（10<sup>-6</sup>）",condition=true,order=true)
    private Double os;
    @GeneratorColumn(title = "铱 Ir（10<sup>-6</sup>）",condition=true,order=true)
    private Double ir;
    @GeneratorColumn(title = "钌 Ru（10<sup>-6</sup>）",condition=true,order=true)
    private Double ru;
    @GeneratorColumn(title = "铑 Rh（10<sup>-6</sup>）",condition=true,order=true)
    private Double rh;
    //上面为微量元素，下面为同位素
    @GeneratorColumn(title = "Sr Isotope",condition=true,order=true,like = true)
    private String srisotope;
    @GeneratorColumn(title = "Nd Isotope",condition=true,order=true,like = true)
    private String ndisotope;
    @GeneratorColumn(title = "(<sup>87</sup>Rb/<sup>86</sup>Sr)m",condition=true,order=true)
    private Double rb87Sr86;
    @GeneratorColumn(title = "(<sup>87</sup>Sr/<sup>86</sup>Sr)m",condition=true,order=true)
    private Double sr87Sr86M;
    @GeneratorColumn(title = "(<sup>147</sup>Sm/<sup>144</sup>Nd)m",condition=true,order=true)
    private Double sm147Nd144;
    @GeneratorColumn(title = "(<sup>143</sup>Nd/<sup>144</sup>Nd)m",condition=true,order=true)
    private Double nd143Nd144;
    @GeneratorColumn(title = "Test Rock (Ma)",condition=true,order=true)
    private Double testRockMa;
    @GeneratorColumn(title = "(<sup>87</sup>Sr/<sup>86</sup>Sr)i",condition=true,order=true)
    private Double sr87Sr86I;
    @GeneratorColumn(title = "(<sup>143</sup>Nd/<sup>144</sup>Nd)t,CHUR",condition=true,order=true)
    private Double nd143Nd144TChur;
    @GeneratorColumn(title = "(<sup>143</sup>Nd/<sup>144</sup>Nd)i",condition=true,order=true)
    private Double nd143Nd144I;
    @GeneratorColumn(title = "f(Sm/Nd)s",condition=true,order=true)
    private Double fSmNdS;
    @GeneratorColumn(title = "εNd(0)",condition=true,order=true)
    private Double epsilonNd0;
    @GeneratorColumn(title = "εNd(t)",condition=true,order=true)
    private Double epsilonNdT;
    @GeneratorColumn(title = "TDM(Ma)",condition=true,order=true)
    private Double tdmMa;
    @GeneratorColumn(title = "TDM2(Ma)",condition=true,order=true)
    private Double tdm2Ma;
    @GeneratorColumn(title = "Hf Isotope",condition=true,order=true,like = true)
    private String hfisotope;
    @GeneratorColumn(title = "Hf Point Number",condition=true,order=true)
    private Integer hfPointnum;
    @GeneratorColumn(title = "Hf Normal Number",condition=true,order=true)
    private Double hfNormalnum;
    @GeneratorColumn(title = "εHft_min",condition=true,order=true)
    private Double epsilonHftMin;
    @GeneratorColumn(title = "εHft_max",condition=true,order=true)
    private Double epsilonHftMax;
    @GeneratorColumn(title = "εHft_median",condition=true,order=true)
    private Double epsilonHftMedian;
    @GeneratorColumn(title = "εHft_average",condition=true,order=true)
    private Double epsilonHftAverage;
    @GeneratorColumn(title = "T<sub>DM</sub><sup>C</sup>_min",condition=true,order=true)
    private Double tdmcMin;
    @GeneratorColumn(title = "T<sub>DM</sub><sup>C</sup>_max",condition=true,order=true)
    private Double tdmcMax;
    @GeneratorColumn(title = "T<sub>DM</sub><sup>C</sup>_median",condition=true,order=true)
    private Double tdmcMedian;
    @GeneratorColumn(title = "T<sub>DM</sub><sup>C</sup>(Ma)_Average",condition=true,order=true)
    private Double tdmcAverage;
    @GeneratorColumn(title = "HfO Isotope",condition=true,order=true,like = true)
    private String hfoisotope;
    @GeneratorColumn(title = "d<sup>18</sup>O_min",condition=true,order=true)
    private Double d18oMin;
    @GeneratorColumn(title = "d<sup>18</sup>O_max",condition=true,order=true)
    private Double d18oMax;
    @GeneratorColumn(title = "d<sup>18</sup>O_average",condition=true,order=true)
    private Double d18oAverage;
    @GeneratorColumn(title = "d<sup>18</sup>O_median",condition=true,order=true)
    private Double d18oMedian;




    public SampleInfo() {
    }


    public SampleInfo(Integer id) {
        this.id = id;
    }
    public SampleInfo(Integer id, String sampleId, String oraginalSampleId, Double longitude, Double latitude, String location, String locationType, String tectonicLocation, String primaryStructuralUnit, String secondaryStructuralUnit, String tertiaryStructuralUnit, String lithology, String occurrence, String intrusion, String rockName, String rockCode, String era, String geobodyName, String geobodyCode, String surroundingRockAge, String surroundingRockLithology, String relationshipWithSurroundingRock, String form, String whetherToCutAreaConstructionLine, String degreeOfDeformation, String characteristicMinerals, String geneticType, Double age, Double ageError, String testObject, String testMethod, Double ageSelected, Double ageSelectedError, String tectonicType, String sourceOfStructuralTypeDiscrimination, String alkalinity, String aluminumQuality, String photo, String collector, String collectorOrg, String reviewer, String analyzeOrg, String analyzePerson, String testDate, String dataSource, String articleDoi, String remark, Double sio2, Double tio2, Double al2o3, Double fe2o3, Double feo, Double fe2o3t, Double feot, Double tfe, Double mno, Double mgo, Double cao, Double na2o, Double k2o, Double p2o5, Double h2op, Double h2on, Double co2, Double so3, Double f, Double cl, Double loi, Double total, Double la, Double ce, Double pr, Double nd, Double pm, Double sm, Double eu, Double gd, Double tb, Double dy, Double ho, Double er, Double tm, Double yb, Double y, Double sc, Double totalReElement, Double v, Double cr, Double co, Double ni, Double mn, Double cu, Double zn, Double ga, Double ge, Double cs, Double rb, Double ba, Double th, Double u, Double nb, Double ta, Double ti, Double p, Double pb, Double sr, Double zr, Double hf, Double li, Double be, Double w, Double pt, Double pd, Double os, Double ir, Double ru, Double rh, Double rb87Sr86, Double sr87Sr86M, Double sm147Nd144, Double nd143Nd144, Double testRockMa, Double sr87Sr86I, Double nd143Nd144TChur, Double nd143Nd144I, Double fSmNdS, Double epsilonNd0, Double epsilonNdT, Double tdmMa, Double tdm2Ma, String hfisotope, Integer hfPointnum, Double hfNormalnum, Double epsilonHftMin, Double epsilonHftMax, Double epsilonHftMedian, Double epsilonHftAverage, Double tdmcMin, Double tdmcMax, Double tdmcMedian, Double tdmcAverage, String hfoisotope, Double d18oMin, Double d18oMax, Double d18oAverage, Double d18oMedian, String regionLocation, String miningArea, String oreType, String pluton, String plutonOrigin, String lithologyOrigin, String refAuthor, String refYear, String refMagazine, String issuePage, String refTitle, String refOrigin, String refMagazineOrigin, String refTitleOrigin, Double lu, String srisotope, String ndisotope) {
        this.id = id;
        this.sampleId = sampleId;
        this.oraginalSampleId = oraginalSampleId;
        this.longitude = longitude;
        this.latitude = latitude;
        this.location = location;
        this.locationType = locationType;
        this.tectonicLocation = tectonicLocation;
        this.primaryStructuralUnit = primaryStructuralUnit;
        this.secondaryStructuralUnit = secondaryStructuralUnit;
        this.tertiaryStructuralUnit = tertiaryStructuralUnit;
        this.lithology = lithology;
        this.occurrence = occurrence;
        this.intrusion = intrusion;
        this.rockName = rockName;
        this.rockCode = rockCode;
        this.era = era;
        this.geobodyName = geobodyName;
        this.geobodyCode = geobodyCode;
        this.surroundingRockAge = surroundingRockAge;
        this.surroundingRockLithology = surroundingRockLithology;
        this.relationshipWithSurroundingRock = relationshipWithSurroundingRock;
        this.form = form;
        this.whetherToCutAreaConstructionLine = whetherToCutAreaConstructionLine;
        this.degreeOfDeformation = degreeOfDeformation;
        this.characteristicMinerals = characteristicMinerals;
        this.geneticType = geneticType;
        this.age = age;
        this.ageError = ageError;
        this.testObject = testObject;
        this.testMethod = testMethod;
        this.ageSelected = ageSelected;
        this.ageSelectedError = ageSelectedError;
        this.tectonicType = tectonicType;
        this.sourceOfStructuralTypeDiscrimination = sourceOfStructuralTypeDiscrimination;
        this.alkalinity = alkalinity;
        this.aluminumQuality = aluminumQuality;
        this.photo = photo;
        this.collector = collector;
        this.collectorOrg = collectorOrg;
        this.reviewer = reviewer;
        this.analyzeOrg = analyzeOrg;
        this.analyzePerson = analyzePerson;
        this.testDate = testDate;
        this.dataSource = dataSource;
        this.articleDoi = articleDoi;
        this.remark = remark;
        this.sio2 = sio2;
        this.tio2 = tio2;
        this.al2o3 = al2o3;
        this.fe2o3 = fe2o3;
        this.feo = feo;
        this.fe2o3t = fe2o3t;
        this.feot = feot;
        this.tfe = tfe;
        this.mno = mno;
        this.mgo = mgo;
        this.cao = cao;
        this.na2o = na2o;
        this.k2o = k2o;
        this.p2o5 = p2o5;
        this.h2op = h2op;
        this.h2on = h2on;
        this.co2 = co2;
        this.so3 = so3;
        this.f = f;
        this.cl = cl;
        this.loi = loi;
        this.total = total;
        this.la = la;
        this.ce = ce;
        this.pr = pr;
        this.nd = nd;
        this.pm = pm;
        this.sm = sm;
        this.eu = eu;
        this.gd = gd;
        this.tb = tb;
        this.dy = dy;
        this.ho = ho;
        this.er = er;
        this.tm = tm;
        this.yb = yb;
        this.y = y;
        this.sc = sc;
        this.totalReElement = totalReElement;
        this.v = v;
        this.cr = cr;
        this.co = co;
        this.ni = ni;
        this.mn = mn;
        this.cu = cu;
        this.zn = zn;
        this.ga = ga;
        this.ge = ge;
        this.cs = cs;
        this.rb = rb;
        this.ba = ba;
        this.th = th;
        this.u = u;
        this.nb = nb;
        this.ta = ta;
        this.ti = ti;
        this.p = p;
        this.pb = pb;
        this.sr = sr;
        this.zr = zr;
        this.hf = hf;
        this.li = li;
        this.be = be;
        this.w = w;
        this.pt = pt;
        this.pd = pd;
        this.os = os;
        this.ir = ir;
        this.ru = ru;
        this.rh = rh;
        this.rb87Sr86 = rb87Sr86;
        this.sr87Sr86M = sr87Sr86M;
        this.sm147Nd144 = sm147Nd144;
        this.nd143Nd144 = nd143Nd144;
        this.testRockMa = testRockMa;
        this.sr87Sr86I = sr87Sr86I;
        this.nd143Nd144TChur = nd143Nd144TChur;
        this.nd143Nd144I = nd143Nd144I;
        this.fSmNdS = fSmNdS;
        this.epsilonNd0 = epsilonNd0;
        this.epsilonNdT = epsilonNdT;
        this.tdmMa = tdmMa;
        this.tdm2Ma = tdm2Ma;
        this.hfisotope = hfisotope;
        this.hfPointnum = hfPointnum;
        this.hfNormalnum = hfNormalnum;
        this.epsilonHftMin = epsilonHftMin;
        this.epsilonHftMax = epsilonHftMax;
        this.epsilonHftMedian = epsilonHftMedian;
        this.epsilonHftAverage = epsilonHftAverage;
        this.tdmcMin = tdmcMin;
        this.tdmcMax = tdmcMax;
        this.tdmcMedian = tdmcMedian;
        this.tdmcAverage = tdmcAverage;
        this.hfoisotope = hfoisotope;
        this.d18oMin = d18oMin;
        this.d18oMax = d18oMax;
        this.d18oAverage = d18oAverage;
        this.d18oMedian = d18oMedian;
        this.regionLocation = regionLocation;
        this.miningArea = miningArea;
        this.oreType = oreType;
        this.pluton = pluton;
        this.plutonOrigin = plutonOrigin;
        this.lithologyOrigin = lithologyOrigin;
        this.refAuthor = refAuthor;
        this.refYear = refYear;
        this.refMagazine = refMagazine;
        this.issuePage = issuePage;
        this.refTitle = refTitle;
        this.refOrigin = refOrigin;
        this.refMagazineOrigin = refMagazineOrigin;
        this.refTitleOrigin = refTitleOrigin;
        this.lu = lu;
        this.srisotope = srisotope;
        this.ndisotope = ndisotope;
    }

    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="sample_id")
    public String getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    @Column(name="oraginal_sample_id")
    public String getOraginalSampleId() {
        return this.oraginalSampleId;
    }

    public void setOraginalSampleId(String oraginalSampleId) {
        this.oraginalSampleId = oraginalSampleId;
    }

    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    @Column(name="location")
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name="region_location")
    public String getRegionLocation() {
        return this.regionLocation;
    }

    public void setRegionLocation(String regionLocation) {
        this.regionLocation = regionLocation;
    }

    @Column(name="location_type")
    public String getLocationType() {
        return this.locationType;
    }

    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }

    @Column(name="tectonic_location")
    public String getTectonicLocation() {
        return this.tectonicLocation;
    }

    public void setTectonicLocation(String tectonicLocation) {
        this.tectonicLocation = tectonicLocation;
    }


    @Column(name="tectonic_type")
    public String getTectonicType() {
        return this.tectonicType;
    }

    public void setTectonicType(String tectonicType) {
        this.tectonicType = tectonicType;
    }


    @Column(name="lithology")
    public String getLithology() {
        return this.lithology;
    }

    public void setLithology(String lithology) {
        this.lithology = lithology;
    }

    @Column(name="lithology_origin")
    public String getLithologyOrigin() {
        return this.lithologyOrigin;
    }

    public void setLithologyOrigin(String lithologyOrigin) {
        this.lithologyOrigin = lithologyOrigin;
    }


    @Column(name="occurrence")
    public String getOccurrence() {
        return this.occurrence;
    }

    public void setOccurrence(String occurrence) {
        this.occurrence = occurrence;
    }

    @Column(name="intrusion")
    public String getIntrusion() {
        return this.intrusion;
    }

    public void setIntrusion(String intrusion) {
        this.intrusion = intrusion;
    }


    @Column(name="pluton")
    public String getPluton() {
        return this.pluton;
    }

    public void setPluton(String pluton) {
        this.pluton = pluton;
    }

    @Column(name="pluton_origin")
    public String getPlutonOrigin() {
        return this.plutonOrigin;
    }

    public void setPlutonOrigin(String plutonOrigin) {
        this.plutonOrigin = plutonOrigin;
    }


    @Column(name="rock_name")
    public String getRockName() {
        return this.rockName;
    }

    public void setRockName(String rockName) {
        this.rockName = rockName;
    }

    @Column(name="rock_code")
    public String getRockCode() {
        return this.rockCode;
    }

    public void setRockCode(String rockCode) {
        this.rockCode = rockCode;
    }

    @Column(name="era")
    public String getEra() {
        return this.era;
    }

    public void setEra(String era) {
        this.era = era;
    }

    @Column(name="geobody_name")
    public String getGeobodyName() {
        return this.geobodyName;
    }

    public void setGeobodyName(String geobodyName) {
        this.geobodyName = geobodyName;
    }

    @Column(name="geobody_code")
    public String getGeobodyCode() {
        return this.geobodyCode;
    }

    public void setGeobodyCode(String geobodyCode) {
        this.geobodyCode = geobodyCode;
    }

    @Column(name="surrounding_rock_age")
    public String getSurroundingRockAge() {
        return this.surroundingRockAge;
    }

    public void setSurroundingRockAge(String surroundingRockAge) {
        this.surroundingRockAge = surroundingRockAge;
    }

    @Column(name="surrounding_rock_lithology")
    public String getSurroundingRockLithology() {
        return this.surroundingRockLithology;
    }

    public void setSurroundingRockLithology(String surroundingRockLithology) {
        this.surroundingRockLithology = surroundingRockLithology;
    }

    @Column(name="relationship_with_surrounding_rock")
    public String getRelationshipWithSurroundingRock() {
        return this.relationshipWithSurroundingRock;
    }

    public void setRelationshipWithSurroundingRock(String relationshipWithSurroundingRock) {
        this.relationshipWithSurroundingRock = relationshipWithSurroundingRock;
    }

    @Column(name="form")
    public String getForm() {
        return this.form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    @Column(name="whether_to_cut_area_construction_line")
    public String getWhetherToCutAreaConstructionLine() {
        return this.whetherToCutAreaConstructionLine;
    }

    public void setWhetherToCutAreaConstructionLine(String whetherToCutAreaConstructionLine) {
        this.whetherToCutAreaConstructionLine = whetherToCutAreaConstructionLine;
    }

    @Column(name="degree_of_deformation")
    public String getDegreeOfDeformation() {
        return this.degreeOfDeformation;
    }

    public void setDegreeOfDeformation(String degreeOfDeformation) {
        this.degreeOfDeformation = degreeOfDeformation;
    }

    @Column(name="characteristic_minerals")
    public String getCharacteristicMinerals() {
        return this.characteristicMinerals;
    }

    public void setCharacteristicMinerals(String characteristicMinerals) {
        this.characteristicMinerals = characteristicMinerals;
    }


    @Column(name="mining_area")
    public String getMiningArea() {
        return this.miningArea;
    }

    public void setMiningArea(String miningArea) {
        this.miningArea = miningArea;
    }

    @Column(name="ore_type")
    public String getOreType() {
        return this.oreType;
    }

    public void setOreType(String oreType) {
        this.oreType = oreType;
    }


    @Column(name="genetic_type")
    public String getGeneticType() {
        return this.geneticType;
    }

    public void setGeneticType(String geneticType) {
        this.geneticType = geneticType;
    }

    @Column(name="age", precision=17, scale=17)
    public Double getAge() {
        return this.age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    @Column(name="age_error", precision=17, scale=17)
    public Double getAgeError() {
        return this.ageError;
    }

    public void setAgeError(Double ageError) {
        this.ageError = ageError;
    }

    @Column(name="age_selected", precision=17, scale=17)
    public Double getAgeSelected() {
        return this.ageSelected;
    }

    public void setAgeSelected(Double ageSelected) {
        this.ageSelected = ageSelected;
    }

    @Column(name="age_selected_error", precision=17, scale=17)
    public Double getAgeSelectedError() {
        return this.ageSelectedError;
    }

    public void setAgeSelectedError(Double ageSelectedError) {
        this.ageSelectedError = ageSelectedError;
    }

    @Column(name="test_object")
    public String getTestObject() {
        return this.testObject;
    }

    public void setTestObject(String testObject) {
        this.testObject = testObject;
    }

    @Column(name="test_method")
    public String getTestMethod() {
        return this.testMethod;
    }

    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod;
    }

    @Column(name="primary_structural_unit")
    public String getPrimaryStructuralUnit() {
        return this.primaryStructuralUnit;
    }

    public void setPrimaryStructuralUnit(String primaryStructuralUnit) {
        this.primaryStructuralUnit = primaryStructuralUnit;
    }

    @Column(name="secondary_structural_unit")
    public String getSecondaryStructuralUnit() {
        return this.secondaryStructuralUnit;
    }

    public void setSecondaryStructuralUnit(String secondaryStructuralUnit) {
        this.secondaryStructuralUnit = secondaryStructuralUnit;
    }

    @Column(name="tertiary_structural_unit")
    public String getTertiaryStructuralUnit() {
        return this.tertiaryStructuralUnit;
    }

    public void setTertiaryStructuralUnit(String tertiaryStructuralUnit) {
        this.tertiaryStructuralUnit = tertiaryStructuralUnit;
    }

    @Column(name="source_of_structural_type_discrimination")
    public String getSourceOfStructuralTypeDiscrimination() {
        return this.sourceOfStructuralTypeDiscrimination;
    }

    public void setSourceOfStructuralTypeDiscrimination(String sourceOfStructuralTypeDiscrimination) {
        this.sourceOfStructuralTypeDiscrimination = sourceOfStructuralTypeDiscrimination;
    }

    @Column(name="alkalinity")
    public String getAlkalinity() {
        return this.alkalinity;
    }

    public void setAlkalinity(String alkalinity) {
        this.alkalinity = alkalinity;
    }

    @Column(name="aluminum_quality")
    public String getAluminumQuality() {
        return this.aluminumQuality;
    }

    public void setAluminumQuality(String aluminumQuality) {
        this.aluminumQuality = aluminumQuality;
    }

    @Column(name="photo")
    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Column(name="collector")
    public String getCollector() {
        return this.collector;
    }

    public void setCollector(String collector) {
        this.collector = collector;
    }

    @Column(name="collector_org")
    public String getCollectorOrg() {
        return this.collectorOrg;
    }

    public void setCollectorOrg(String collectorOrg) {
        this.collectorOrg = collectorOrg;
    }

    @Column(name="reviewer")
    public String getReviewer() {
        return this.reviewer;
    }

    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }

    @Column(name="analyze_org")
    public String getAnalyzeOrg() {
        return this.analyzeOrg;
    }

    public void setAnalyzeOrg(String analyzeOrg) {
        this.analyzeOrg = analyzeOrg;
    }

    @Column(name="analyze_person")
    public String getAnalyzePerson() {
        return this.analyzePerson;
    }

    public void setAnalyzePerson(String analyzePerson) {
        this.analyzePerson = analyzePerson;
    }

    @Column(name="test_date")
    public String getTestDate() {
        return this.testDate;
    }

    public void setTestDate(String testDate) {
        this.testDate = testDate;
    }

    @Column(name="data_source")
    public String getDataSource() {
        return this.dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    @Column(name="article_doi")
    public String getArticleDoi() {
        return this.articleDoi;
    }

    public void setArticleDoi(String articleDoi) {
        this.articleDoi = articleDoi;
    }

    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }


    @Column(name="ref_author")
    public String getRefAuthor() {
        return this.refAuthor;
    }

    public void setRefAuthor(String refAuthor) {
        this.refAuthor = refAuthor;
    }

    @Column(name="ref_year")
    public String getRefYear() {
        return this.refYear;
    }

    public void setRefYear(String refYear) {
        this.refYear = refYear;
    }

    @Column(name="ref_magazine")
    public String getRefMagazine() {
        return this.refMagazine;
    }

    public void setRefMagazine(String refMagazine) {
        this.refMagazine = refMagazine;
    }

    @Column(name="issue_page")
    public String getIssuePage() {
        return this.issuePage;
    }

    public void setIssuePage(String issuePage) {
        this.issuePage = issuePage;
    }

    @Column(name="ref_title")
    public String getRefTitle() {
        return this.refTitle;
    }

    public void setRefTitle(String refTitle) {
        this.refTitle = refTitle;
    }

    @Column(name="ref_origin")
    public String getRefOrigin() {
        return this.refOrigin;
    }

    public void setRefOrigin(String refOrigin) {
        this.refOrigin = refOrigin;
    }

    @Column(name="ref_magazine_origin")
    public String getRefMagazineOrigin() {
        return this.refMagazineOrigin;
    }

    public void setRefMagazineOrigin(String refMagazineOrigin) {
        this.refMagazineOrigin = refMagazineOrigin;
    }

    @Column(name="ref_title_origin")
    public String getRefTitleOrigin() {
        return this.refTitleOrigin;
    }

    public void setRefTitleOrigin(String refTitleOrigin) {
        this.refTitleOrigin = refTitleOrigin;
    }


    @Column(name="sio2", precision=17, scale=17)
    public Double getSio2() {
        return this.sio2;
    }

    public void setSio2(Double sio2) {
        this.sio2 = sio2;
    }

    @Column(name="tio2", precision=17, scale=17)
    public Double getTio2() {
        return this.tio2;
    }

    public void setTio2(Double tio2) {
        this.tio2 = tio2;
    }

    @Column(name="al2o3", precision=17, scale=17)
    public Double getAl2o3() {
        return this.al2o3;
    }

    public void setAl2o3(Double al2o3) {
        this.al2o3 = al2o3;
    }

    @Column(name="fe2o3", precision=17, scale=17)
    public Double getFe2o3() {
        return this.fe2o3;
    }

    public void setFe2o3(Double fe2o3) {
        this.fe2o3 = fe2o3;
    }

    @Column(name="feo", precision=17, scale=17)
    public Double getFeo() {
        return this.feo;
    }

    public void setFeo(Double feo) {
        this.feo = feo;
    }

    @Column(name="fe2o3t", precision=17, scale=17)
    public Double getFe2o3t() {
        return this.fe2o3t;
    }

    public void setFe2o3t(Double fe2o3t) {
        this.fe2o3t = fe2o3t;
    }

    @Column(name="feot", precision=17, scale=17)
    public Double getFeot() {
        return this.feot;
    }

    public void setFeot(Double feot) {
        this.feot = feot;
    }

    @Column(name="tfe", precision=17, scale=17)
    public Double getTfe() {
        return this.tfe;
    }

    public void setTfe(Double tfe) {
        this.tfe = tfe;
    }

    @Column(name="mno", precision=17, scale=17)
    public Double getMno() {
        return this.mno;
    }

    public void setMno(Double mno) {
        this.mno = mno;
    }

    @Column(name="mgo", precision=17, scale=17)
    public Double getMgo() {
        return this.mgo;
    }

    public void setMgo(Double mgo) {
        this.mgo = mgo;
    }

    @Column(name="cao", precision=17, scale=17)
    public Double getCao() {
        return this.cao;
    }

    public void setCao(Double cao) {
        this.cao = cao;
    }

    @Column(name="na2o", precision=17, scale=17)
    public Double getNa2o() {
        return this.na2o;
    }

    public void setNa2o(Double na2o) {
        this.na2o = na2o;
    }

    @Column(name="k2o", precision=17, scale=17)
    public Double getK2o() {
        return this.k2o;
    }

    public void setK2o(Double k2o) {
        this.k2o = k2o;
    }

    @Column(name="p2o5", precision=17, scale=17)
    public Double getP2o5() {
        return this.p2o5;
    }

    public void setP2o5(Double p2o5) {
        this.p2o5 = p2o5;
    }

    @Column(name="h2op", precision=17, scale=17)
    public Double getH2op() {
        return this.h2op;
    }

    public void setH2op(Double h2op) {
        this.h2op = h2op;
    }

    @Column(name="h2on", precision=17, scale=17)
    public Double getH2on() {
        return this.h2on;
    }

    public void setH2on(Double h2on) {
        this.h2on = h2on;
    }

    @Column(name="co2", precision=17, scale=17)
    public Double getCo2() {
        return this.co2;
    }

    public void setCo2(Double co2) {
        this.co2 = co2;
    }

    @Column(name="so3", precision=17, scale=17)
    public Double getSo3() {
        return this.so3;
    }

    public void setSo3(Double so3) {
        this.so3 = so3;
    }

    @Column(name="f", precision=17, scale=17)
    public Double getF() {
        return this.f;
    }

    public void setF(Double f) {
        this.f = f;
    }

    @Column(name="cl", precision=17, scale=17)
    public Double getCl() {
        return this.cl;
    }

    public void setCl(Double cl) {
        this.cl = cl;
    }

    @Column(name="loi", precision=17, scale=17)
    public Double getLoi() {
        return this.loi;
    }

    public void setLoi(Double loi) {
        this.loi = loi;
    }

    @Column(name="total", precision=17, scale=17)
    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    @Column(name="la", precision=17, scale=17)
    public Double getLa() {
        return this.la;
    }

    public void setLa(Double la) {
        this.la = la;
    }

    @Column(name="ce", precision=17, scale=17)
    public Double getCe() {
        return this.ce;
    }

    public void setCe(Double ce) {
        this.ce = ce;
    }

    @Column(name="pr", precision=17, scale=17)
    public Double getPr() {
        return this.pr;
    }

    public void setPr(Double pr) {
        this.pr = pr;
    }

    @Column(name="nd", precision=17, scale=17)
    public Double getNd() {
        return this.nd;
    }

    public void setNd(Double nd) {
        this.nd = nd;
    }


    @Column(name="sm", precision=17, scale=17)
    public Double getSm() {
        return this.sm;
    }

    public void setSm(Double sm) {
        this.sm = sm;
    }

    @Column(name="eu", precision=17, scale=17)
    public Double getEu() {
        return this.eu;
    }

    public void setEu(Double eu) {
        this.eu = eu;
    }

    @Column(name="gd", precision=17, scale=17)
    public Double getGd() {
        return this.gd;
    }

    public void setGd(Double gd) {
        this.gd = gd;
    }

    @Column(name="tb", precision=17, scale=17)
    public Double getTb() {
        return this.tb;
    }

    public void setTb(Double tb) {
        this.tb = tb;
    }

    @Column(name="dy", precision=17, scale=17)
    public Double getDy() {
        return this.dy;
    }

    public void setDy(Double dy) {
        this.dy = dy;
    }

    @Column(name="ho", precision=17, scale=17)
    public Double getHo() {
        return this.ho;
    }

    public void setHo(Double ho) {
        this.ho = ho;
    }

    @Column(name="er", precision=17, scale=17)
    public Double getEr() {
        return this.er;
    }

    public void setEr(Double er) {
        this.er = er;
    }

    @Column(name="tm", precision=17, scale=17)
    public Double getTm() {
        return this.tm;
    }

    public void setTm(Double tm) {
        this.tm = tm;
    }

    @Column(name="yb", precision=17, scale=17)
    public Double getYb() {
        return this.yb;
    }

    public void setYb(Double yb) {
        this.yb = yb;
    }


    @Column(name="lu", precision=17, scale=17)
    public Double getLu() {
        return this.lu;
    }

    public void setLu(Double lu) {
        this.lu = lu;
    }


    @Column(name="y", precision=17, scale=17)
    public Double getY() {
        return this.y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    @Column(name="sc", precision=17, scale=17)
    public Double getSc() {
        return this.sc;
    }

    public void setSc(Double sc) {
        this.sc = sc;
    }

    @Column(name="pm", precision=17, scale=17)
    public Double getPm() {
        return this.pm;
    }

    public void setPm(Double pm) {
        this.pm = pm;
    }

    @Column(name="total_re_element", precision=17, scale=17)
    public Double getTotalReElement() {
        return this.totalReElement;
    }

    public void setTotalReElement(Double totalReElement) {
        this.totalReElement = totalReElement;
    }

    @Column(name="v", precision=17, scale=17)
    public Double getV() {
        return this.v;
    }

    public void setV(Double v) {
        this.v = v;
    }

    @Column(name="cr", precision=17, scale=17)
    public Double getCr() {
        return this.cr;
    }

    public void setCr(Double cr) {
        this.cr = cr;
    }

    @Column(name="co", precision=17, scale=17)
    public Double getCo() {
        return this.co;
    }

    public void setCo(Double co) {
        this.co = co;
    }

    @Column(name="ni", precision=17, scale=17)
    public Double getNi() {
        return this.ni;
    }

    public void setNi(Double ni) {
        this.ni = ni;
    }

    @Column(name="mn", precision=17, scale=17)
    public Double getMn() {
        return this.mn;
    }

    public void setMn(Double mn) {
        this.mn = mn;
    }

    @Column(name="cu", precision=17, scale=17)
    public Double getCu() {
        return this.cu;
    }

    public void setCu(Double cu) {
        this.cu = cu;
    }

    @Column(name="zn", precision=17, scale=17)
    public Double getZn() {
        return this.zn;
    }

    public void setZn(Double zn) {
        this.zn = zn;
    }

    @Column(name="ga", precision=17, scale=17)
    public Double getGa() {
        return this.ga;
    }

    public void setGa(Double ga) {
        this.ga = ga;
    }

    @Column(name="ge", precision=17, scale=17)
    public Double getGe() {
        return this.ge;
    }

    public void setGe(Double ge) {
        this.ge = ge;
    }

    @Column(name="cs", precision=17, scale=17)
    public Double getCs() {
        return this.cs;
    }

    public void setCs(Double cs) {
        this.cs = cs;
    }

    @Column(name="rb", precision=17, scale=17)
    public Double getRb() {
        return this.rb;
    }

    public void setRb(Double rb) {
        this.rb = rb;
    }

    @Column(name="ba", precision=17, scale=17)
    public Double getBa() {
        return this.ba;
    }

    public void setBa(Double ba) {
        this.ba = ba;
    }

    @Column(name="th", precision=17, scale=17)
    public Double getTh() {
        return this.th;
    }

    public void setTh(Double th) {
        this.th = th;
    }

    @Column(name="u", precision=17, scale=17)
    public Double getU() {
        return this.u;
    }

    public void setU(Double u) {
        this.u = u;
    }

    @Column(name="nb", precision=17, scale=17)
    public Double getNb() {
        return this.nb;
    }

    public void setNb(Double nb) {
        this.nb = nb;
    }

    @Column(name="ta", precision=17, scale=17)
    public Double getTa() {
        return this.ta;
    }

    public void setTa(Double ta) {
        this.ta = ta;
    }

    @Column(name="ti", precision=17, scale=17)
    public Double getTi() {
        return this.ti;
    }

    public void setTi(Double ti) {
        this.ti = ti;
    }

    @Column(name="p", precision=17, scale=17)
    public Double getP() {
        return this.p;
    }

    public void setP(Double p) {
        this.p = p;
    }

    @Column(name="pb", precision=17, scale=17)
    public Double getPb() {
        return this.pb;
    }

    public void setPb(Double pb) {
        this.pb = pb;
    }

    @Column(name="sr", precision=17, scale=17)
    public Double getSr() {
        return this.sr;
    }

    public void setSr(Double sr) {
        this.sr = sr;
    }

    @Column(name="zr", precision=17, scale=17)
    public Double getZr() {
        return this.zr;
    }

    public void setZr(Double zr) {
        this.zr = zr;
    }

    @Column(name="hf", precision=17, scale=17)
    public Double getHf() {
        return this.hf;
    }

    public void setHf(Double hf) {
        this.hf = hf;
    }

    @Column(name="li", precision=17, scale=17)
    public Double getLi() {
        return this.li;
    }

    public void setLi(Double li) {
        this.li = li;
    }

    @Column(name="be", precision=17, scale=17)
    public Double getBe() {
        return this.be;
    }

    public void setBe(Double be) {
        this.be = be;
    }

    @Column(name="w", precision=17, scale=17)
    public Double getW() {
        return this.w;
    }

    public void setW(Double w) {
        this.w = w;
    }

    @Column(name="pt", precision=17, scale=17)
    public Double getPt() {
        return this.pt;
    }

    public void setPt(Double pt) {
        this.pt = pt;
    }

    @Column(name="pd", precision=17, scale=17)
    public Double getPd() {
        return this.pd;
    }

    public void setPd(Double pd) {
        this.pd = pd;
    }

    @Column(name="os", precision=17, scale=17)
    public Double getOs() {
        return this.os;
    }

    public void setOs(Double os) {
        this.os = os;
    }

    @Column(name="ir", precision=17, scale=17)
    public Double getIr() {
        return this.ir;
    }

    public void setIr(Double ir) {
        this.ir = ir;
    }

    @Column(name="ru", precision=17, scale=17)
    public Double getRu() {
        return this.ru;
    }

    public void setRu(Double ru) {
        this.ru = ru;
    }

    @Column(name="rh", precision=17, scale=17)
    public Double getRh() {
        return this.rh;
    }

    public void setRh(Double rh) {
        this.rh = rh;
    }

    @Column(name="srisotope")
    public String getSrisotope() {
        return this.srisotope;
    }

    public void setSrisotope(String srisotope) {
        this.srisotope = srisotope;
    }

    @Column(name="ndisotope")
    public String getNdisotope() {
        return this.ndisotope;
    }

    public void setNdisotope(String ndisotope) {
        this.ndisotope = ndisotope;
    }

    @Column(name="rb87_sr86", precision=17, scale=17)
    public Double getRb87Sr86() {
        return this.rb87Sr86;
    }

    public void setRb87Sr86(Double rb87Sr86) {
        this.rb87Sr86 = rb87Sr86;
    }

    @Column(name="sr87_sr86_m", precision=17, scale=17)
    public Double getSr87Sr86M() {
        return this.sr87Sr86M;
    }

    public void setSr87Sr86M(Double sr87Sr86M) {
        this.sr87Sr86M = sr87Sr86M;
    }

    @Column(name="sm147_nd144", precision=17, scale=17)
    public Double getSm147Nd144() {
        return this.sm147Nd144;
    }

    public void setSm147Nd144(Double sm147Nd144) {
        this.sm147Nd144 = sm147Nd144;
    }

    @Column(name="nd143_nd144", precision=17, scale=17)
    public Double getNd143Nd144() {
        return this.nd143Nd144;
    }

    public void setNd143Nd144(Double nd143Nd144) {
        this.nd143Nd144 = nd143Nd144;
    }

    @Column(name="test_rock_ma", precision=17, scale=17)
    public Double getTestRockMa() {
        return this.testRockMa;
    }

    public void setTestRockMa(Double testRockMa) {
        this.testRockMa = testRockMa;
    }

    @Column(name="sr87_sr86_i", precision=17, scale=17)
    public Double getSr87Sr86I() {
        return this.sr87Sr86I;
    }

    public void setSr87Sr86I(Double sr87Sr86I) {
        this.sr87Sr86I = sr87Sr86I;
    }

    @Column(name="nd143_nd144_t_chur", precision=17, scale=17)
    public Double getNd143Nd144TChur() {
        return this.nd143Nd144TChur;
    }

    public void setNd143Nd144TChur(Double nd143Nd144TChur) {
        this.nd143Nd144TChur = nd143Nd144TChur;
    }

    @Column(name="nd143_nd144_i", precision=17, scale=17)
    public Double getNd143Nd144I() {
        return this.nd143Nd144I;
    }

    public void setNd143Nd144I(Double nd143Nd144I) {
        this.nd143Nd144I = nd143Nd144I;
    }

    @Column(name="f_sm_nd_s", precision=17, scale=17)
    public Double getFSmNdS() {
        return this.fSmNdS;
    }

    public void setFSmNdS(Double fSmNdS) {
        this.fSmNdS = fSmNdS;
    }

    @Column(name="epsilon_nd_0", precision=17, scale=17)
    public Double getEpsilonNd0() {
        return this.epsilonNd0;
    }

    public void setEpsilonNd0(Double epsilonNd0) {
        this.epsilonNd0 = epsilonNd0;
    }

    @Column(name="epsilon_nd_t", precision=17, scale=17)
    public Double getEpsilonNdT() {
        return this.epsilonNdT;
    }

    public void setEpsilonNdT(Double epsilonNdT) {
        this.epsilonNdT = epsilonNdT;
    }

    @Column(name="tdm_ma", precision=17, scale=17)
    public Double getTdmMa() {
        return this.tdmMa;
    }

    public void setTdmMa(Double tdmMa) {
        this.tdmMa = tdmMa;
    }

    @Column(name="tdm2_ma", precision=17, scale=17)
    public Double getTdm2Ma() {
        return this.tdm2Ma;
    }

    public void setTdm2Ma(Double tdm2Ma) {
        this.tdm2Ma = tdm2Ma;
    }

    @Column(name="hfisotope")
    public String getHfisotope() {
        return this.hfisotope;
    }

    public void setHfisotope(String hfisotope) {
        this.hfisotope = hfisotope;
    }

    @Column(name="hf_pointnum")
    public Integer getHfPointnum() {
        return this.hfPointnum;
    }

    public void setHfPointnum(Integer hfPointnum) {
        this.hfPointnum = hfPointnum;
    }

    @Column(name="hf_normalnum", precision=17, scale=17)
    public Double getHfNormalnum() {
        return this.hfNormalnum;
    }

    public void setHfNormalnum(Double hfNormalnum) {
        this.hfNormalnum = hfNormalnum;
    }

    @Column(name="epsilon_hft_min", precision=17, scale=17)
    public Double getEpsilonHftMin() {
        return this.epsilonHftMin;
    }

    public void setEpsilonHftMin(Double epsilonHftMin) {
        this.epsilonHftMin = epsilonHftMin;
    }

    @Column(name="epsilon_hft_max", precision=17, scale=17)
    public Double getEpsilonHftMax() {
        return this.epsilonHftMax;
    }

    public void setEpsilonHftMax(Double epsilonHftMax) {
        this.epsilonHftMax = epsilonHftMax;
    }

    @Column(name="epsilon_hft_median", precision=17, scale=17)
    public Double getEpsilonHftMedian() {
        return this.epsilonHftMedian;
    }

    public void setEpsilonHftMedian(Double epsilonHftMedian) {
        this.epsilonHftMedian = epsilonHftMedian;
    }

    @Column(name="epsilon_hft_average", precision=17, scale=17)
    public Double getEpsilonHftAverage() {
        return this.epsilonHftAverage;
    }

    public void setEpsilonHftAverage(Double epsilonHftAverage) {
        this.epsilonHftAverage = epsilonHftAverage;
    }

    @Column(name="tdmc_min", precision=17, scale=17)
    public Double getTdmcMin() {
        return this.tdmcMin;
    }

    public void setTdmcMin(Double tdmcMin) {
        this.tdmcMin = tdmcMin;
    }

    @Column(name="tdmc_max", precision=17, scale=17)
    public Double getTdmcMax() {
        return this.tdmcMax;
    }

    public void setTdmcMax(Double tdmcMax) {
        this.tdmcMax = tdmcMax;
    }

    @Column(name="tdmc_median", precision=17, scale=17)
    public Double getTdmcMedian() {
        return this.tdmcMedian;
    }

    public void setTdmcMedian(Double tdmcMedian) {
        this.tdmcMedian = tdmcMedian;
    }

    @Column(name="tdmc_average", precision=17, scale=17)
    public Double getTdmcAverage() {
        return this.tdmcAverage;
    }

    public void setTdmcAverage(Double tdmcAverage) {
        this.tdmcAverage = tdmcAverage;
    }

    @Column(name="hfoisotope")
    public String getHfoisotope() {
        return this.hfoisotope;
    }

    public void setHfoisotope(String hfoisotope) {
        this.hfoisotope = hfoisotope;
    }

    @Column(name="d18o_min", precision=17, scale=17)
    public Double getD18oMin() {
        return this.d18oMin;
    }

    public void setD18oMin(Double d18oMin) {
        this.d18oMin = d18oMin;
    }

    @Column(name="d18o_max", precision=17, scale=17)
    public Double getD18oMax() {
        return this.d18oMax;
    }

    public void setD18oMax(Double d18oMax) {
        this.d18oMax = d18oMax;
    }

    @Column(name="d18o_average", precision=17, scale=17)
    public Double getD18oAverage() {
        return this.d18oAverage;
    }

    public void setD18oAverage(Double d18oAverage) {
        this.d18oAverage = d18oAverage;
    }

    @Column(name="d18o_median", precision=17, scale=17)
    public Double getD18oMedian() {
        return this.d18oMedian;
    }

    public void setD18oMedian(Double d18oMedian) {
        this.d18oMedian = d18oMedian;
    }

}


