package cn.ac.cags.entities.dde;
// Generated 2021-5-9 15:16:00 by Hibernate Tools 6.0.0-SNAPSHOT


import com.publiccms.common.database.CmsUpgrader;
import com.publiccms.common.generator.annotation.GeneratorColumn;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * Zircon generated by hbm2java
 */
@Entity
@Table(name="zircon"
    ,schema="public"
)
public class Zircon  implements java.io.Serializable {

     /**
     *
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID",order=true)
    private Integer id;
    @GeneratorColumn(title = "Sample Id", condition = true,order=true,like = true)
    private String sampleId;
    @GeneratorColumn(title = "Oraginal Sample Id", condition = true,order=true,like = true)
    private String oraginalSampleId;
    @GeneratorColumn(title = "Point Num", condition = true,order=true,like = true)
    private String pointNum;
    @GeneratorColumn(title = "Hf Type", condition = true,order=true,like = true)
    private String hfType;
    @GeneratorColumn(title = "Test Age（Ma）", condition = true,order=true)
    private Double testAge;
    @GeneratorColumn(title = "<sup>176</sup>Yb/<sup>177</sup>Hf", condition = true,order=true)
    private Double yb176Hf177;
    @GeneratorColumn(title = "<sup>176</sup>Lu/<sup>177</sup>Hf", condition = true,order=true)
    private Double lu176Hf177;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double sigma2LuHf;
    @GeneratorColumn(title = "<sup>176</sup>Hf/<sup>177</sup>Hf", condition = true,order=true)
    private Double hf176Hf177;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double sigma2HfHf;
    @GeneratorColumn(title = "<sup>176</sup>Hf/<sup>177</sup>Hf（t）", condition = true,order=true)
    private Double hf176Hf177T;
    @GeneratorColumn(title = "CHUR（t）", condition = true,order=true)
    private Double churT;
    @GeneratorColumn(title = "DM（t）", condition = true,order=true)
    private Double dmT;
    @GeneratorColumn(title = "εHf(t)", condition = true,order=true)
    private Double epsilonHfT;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double sigma2EpsilonHfT;
    @GeneratorColumn(title = "f<sub>Lu/Hf</sub>", condition = true,order=true)
    private Double FLuHf;
    @GeneratorColumn(title = "T<sub>DM1</sub>", condition = true,order=true)
    private Double tdm1;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double sigma2Tdm1;
    @GeneratorColumn(title = "T<sub>DM2</sub>", condition = true,order=true)
    private Double tdm2;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double sigma2Tdm2;
    @GeneratorColumn(title = "εHf(0)", condition = true,order=true)
    private Double epsilonHf0;
    @GeneratorColumn(title = "d18O", condition = true,order=true)
    private Double d18o;
    @GeneratorColumn(title = "2σ Error", condition = true,order=true)
    private Double epsilonD180;
    @GeneratorColumn(title = "d18O Control", condition = true,order=true)
    private Double epsilonD18oControl;
    @GeneratorColumn(title = "SiO<sub>2</sub>", condition = true,order=true)
    private Double siO2;
    @GeneratorColumn(title = "lithology", condition = true,order=true,like = true)
    private String lithology;
    @GeneratorColumn(title = "Mineral Type", condition = true,order=true,like = true)
    private String mineralType;
    @GeneratorColumn(title = "Number of Grains", condition = true,order=true)
    private Double grainsNumber;
    @GeneratorColumn(title = "P(χ2) (%)", condition = true,order=true)
    private Double chiSquareProbability;
    @GeneratorColumn(title = "Central Age(Ma)", condition = true,order=true)
    private Double centralAge;
    @GeneratorColumn(title = "Central Age Error (Ma)", condition = true,order=true)
    private Double centralAgeError;
    @GeneratorColumn(title = "Pooled Age (Ma)", condition = true,order=true)
    private Double pooledAge;
    @GeneratorColumn(title = "Pooled Age Error (Ma)", condition = true,order=true)
    private Double pooledAgeError;
    @GeneratorColumn(title = "Mean Track Length (cm)", condition = true,order=true)
    private Double meanTrackLength;
    @GeneratorColumn(title = "Length Error (cm)", condition = true,order=true)
    private Double lengthError;
    @GeneratorColumn(title = "(U-Th)/He（Ma）", condition = true,order=true)
    private Double UThHeAge;
    @GeneratorColumn(title = "(U-Th)/He Error（Ma）", condition = true,order=true)
    private Double UThHeAgeError;
    @GeneratorColumn(title = "Article Ref", condition = true,order=true,like = true)
    private String articleRef;
    @GeneratorColumn(title = "Article DOI", condition = true,order=true,like = true)
    private String articleDoi;

    public Zircon() {
    }

	
    public Zircon(Integer id) {
        this.id = id;
    }
    public Zircon(Integer id, String sampleId, String oraginalSampleId, String pointNum, String hfType, Double testAge, Double yb176Hf177, Double lu176Hf177, Double sigma2LuHf, Double hf176Hf177, Double sigma2HfHf, Double hf176Hf177T, Double churT, Double dmT, Double epsilonHfT, Double sigma2EpsilonHfT, Double FLuHf, Double tdm1, Double sigma2Tdm1, Double tdm2, Double sigma2Tdm2, Double epsilonHf0, Double d18o, Double epsilonD180, Double epsilonD18oControl, Double siO2, String lithology, String mineralType, Double grainsNumber, Double chiSquareProbability, Double centralAge, Double centralAgeError, Double pooledAge, Double pooledAgeError, Double meanTrackLength, Double lengthError, Double UThHeAge, Double UThHeAgeError, String articleRef, String articleDoi) {
       this.id = id;
       this.sampleId = sampleId;
       this.oraginalSampleId = oraginalSampleId;
       this.pointNum = pointNum;
       this.hfType = hfType;
       this.testAge = testAge;
       this.yb176Hf177 = yb176Hf177;
       this.lu176Hf177 = lu176Hf177;
       this.sigma2LuHf = sigma2LuHf;
       this.hf176Hf177 = hf176Hf177;
       this.sigma2HfHf = sigma2HfHf;
       this.hf176Hf177T = hf176Hf177T;
       this.churT = churT;
       this.dmT = dmT;
       this.epsilonHfT = epsilonHfT;
       this.sigma2EpsilonHfT = sigma2EpsilonHfT;
       this.FLuHf = FLuHf;
       this.tdm1 = tdm1;
       this.sigma2Tdm1 = sigma2Tdm1;
       this.tdm2 = tdm2;
       this.sigma2Tdm2 = sigma2Tdm2;
       this.epsilonHf0 = epsilonHf0;
       this.d18o = d18o;
       this.epsilonD180 = epsilonD180;
       this.epsilonD18oControl = epsilonD18oControl;
       this.siO2 = siO2;
       this.lithology = lithology;
       this.mineralType = mineralType;
       this.grainsNumber = grainsNumber;
       this.chiSquareProbability = chiSquareProbability;
       this.centralAge = centralAge;
       this.centralAgeError = centralAgeError;
       this.pooledAge = pooledAge;
       this.pooledAgeError = pooledAgeError;
       this.meanTrackLength = meanTrackLength;
       this.lengthError = lengthError;
       this.UThHeAge = UThHeAge;
       this.UThHeAgeError = UThHeAgeError;
       this.articleRef = articleRef;
       this.articleDoi = articleDoi;
    }
   
    @Id
    @GeneratedValue(generator = "cmsGenerator")
    @GenericGenerator(name = "cmsGenerator", strategy = CmsUpgrader.IDENTIFIER_GENERATOR)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="\"Sample_Id\"")
    public String getSampleId() {
        return this.sampleId;
    }
    
    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }
    
    @Column(name="\"Oraginal_Sample_Id\"")
    public String getOraginalSampleId() {
        return this.oraginalSampleId;
    }
    
    public void setOraginalSampleId(String oraginalSampleId) {
        this.oraginalSampleId = oraginalSampleId;
    }
    
    @Column(name="\"PointNum\"")
    public String getPointNum() {
        return this.pointNum;
    }
    
    public void setPointNum(String pointNum) {
        this.pointNum = pointNum;
    }
    
    @Column(name="\"HfType\"")
    public String getHfType() {
        return this.hfType;
    }
    
    public void setHfType(String hfType) {
        this.hfType = hfType;
    }
    
    @Column(name="\"TestAge\"", precision=17, scale=17)
    public Double getTestAge() {
        return this.testAge;
    }
    
    public void setTestAge(Double testAge) {
        this.testAge = testAge;
    }
    
    @Column(name="\"Yb176_Hf177\"", precision=17, scale=17)
    public Double getYb176Hf177() {
        return this.yb176Hf177;
    }
    
    public void setYb176Hf177(Double yb176Hf177) {
        this.yb176Hf177 = yb176Hf177;
    }
    
    @Column(name="\"Lu176_Hf177\"", precision=17, scale=17)
    public Double getLu176Hf177() {
        return this.lu176Hf177;
    }
    
    public void setLu176Hf177(Double lu176Hf177) {
        this.lu176Hf177 = lu176Hf177;
    }
    
    @Column(name="\"sigma2_LuHf\"", precision=17, scale=17)
    public Double getSigma2LuHf() {
        return this.sigma2LuHf;
    }
    
    public void setSigma2LuHf(Double sigma2LuHf) {
        this.sigma2LuHf = sigma2LuHf;
    }
    
    @Column(name="\"Hf176_Hf177\"", precision=17, scale=17)
    public Double getHf176Hf177() {
        return this.hf176Hf177;
    }
    
    public void setHf176Hf177(Double hf176Hf177) {
        this.hf176Hf177 = hf176Hf177;
    }
    
    @Column(name="\"sigma2_HfHf\"", precision=17, scale=17)
    public Double getSigma2HfHf() {
        return this.sigma2HfHf;
    }
    
    public void setSigma2HfHf(Double sigma2HfHf) {
        this.sigma2HfHf = sigma2HfHf;
    }
    
    @Column(name="\"Hf176_Hf177_t\"", precision=17, scale=17)
    public Double getHf176Hf177T() {
        return this.hf176Hf177T;
    }
    
    public void setHf176Hf177T(Double hf176Hf177T) {
        this.hf176Hf177T = hf176Hf177T;
    }
    
    @Column(name="\"CHUR_t\"", precision=17, scale=17)
    public Double getChurT() {
        return this.churT;
    }
    
    public void setChurT(Double churT) {
        this.churT = churT;
    }
    
    @Column(name="\"DM_t\"", precision=17, scale=17)
    public Double getDmT() {
        return this.dmT;
    }
    
    public void setDmT(Double dmT) {
        this.dmT = dmT;
    }
    
    @Column(name="\"epsilon_Hf_t\"", precision=17, scale=17)
    public Double getEpsilonHfT() {
        return this.epsilonHfT;
    }
    
    public void setEpsilonHfT(Double epsilonHfT) {
        this.epsilonHfT = epsilonHfT;
    }
    
    @Column(name="\"sigma2_epsilon_hf_t\"", precision=17, scale=17)
    public Double getSigma2EpsilonHfT() {
        return this.sigma2EpsilonHfT;
    }
    
    public void setSigma2EpsilonHfT(Double sigma2EpsilonHfT) {
        this.sigma2EpsilonHfT = sigma2EpsilonHfT;
    }
    
    @Column(name="\"F_Lu_Hf\"", precision=17, scale=17)
    public Double getFLuHf() {
        return this.FLuHf;
    }
    
    public void setFLuHf(Double FLuHf) {
        this.FLuHf = FLuHf;
    }
    
    @Column(name="\"TDM1\"", precision=17, scale=17)
    public Double getTdm1() {
        return this.tdm1;
    }
    
    public void setTdm1(Double tdm1) {
        this.tdm1 = tdm1;
    }
    
    @Column(name="\"sigma2_TDM1\"", precision=17, scale=17)
    public Double getSigma2Tdm1() {
        return this.sigma2Tdm1;
    }
    
    public void setSigma2Tdm1(Double sigma2Tdm1) {
        this.sigma2Tdm1 = sigma2Tdm1;
    }
    
    @Column(name="\"TDM2\"", precision=17, scale=17)
    public Double getTdm2() {
        return this.tdm2;
    }
    
    public void setTdm2(Double tdm2) {
        this.tdm2 = tdm2;
    }
    
    @Column(name="\"sigma2_TDM2\"", precision=17, scale=17)
    public Double getSigma2Tdm2() {
        return this.sigma2Tdm2;
    }
    
    public void setSigma2Tdm2(Double sigma2Tdm2) {
        this.sigma2Tdm2 = sigma2Tdm2;
    }
    
    @Column(name="\"epsilon_Hf_0\"", precision=17, scale=17)
    public Double getEpsilonHf0() {
        return this.epsilonHf0;
    }
    
    public void setEpsilonHf0(Double epsilonHf0) {
        this.epsilonHf0 = epsilonHf0;
    }
    
    @Column(name="\"d18O\"", precision=17, scale=17)
    public Double getD18o() {
        return this.d18o;
    }
    
    public void setD18o(Double d18o) {
        this.d18o = d18o;
    }
    
    @Column(name="\"epsilon_d180\"", precision=17, scale=17)
    public Double getEpsilonD180() {
        return this.epsilonD180;
    }
    
    public void setEpsilonD180(Double epsilonD180) {
        this.epsilonD180 = epsilonD180;
    }
    
    @Column(name="\"epsilon_d18o_control\"", precision=17, scale=17)
    public Double getEpsilonD18oControl() {
        return this.epsilonD18oControl;
    }
    
    public void setEpsilonD18oControl(Double epsilonD18oControl) {
        this.epsilonD18oControl = epsilonD18oControl;
    }
    
    @Column(name="\"SiO2\"", precision=17, scale=17)
    public Double getSiO2() {
        return this.siO2;
    }
    
    public void setSiO2(Double siO2) {
        this.siO2 = siO2;
    }
    
    @Column(name="\"Lithology\"")
    public String getLithology() {
        return this.lithology;
    }
    
    public void setLithology(String lithology) {
        this.lithology = lithology;
    }
    
    @Column(name="\"Mineral_type\"")
    public String getMineralType() {
        return this.mineralType;
    }
    
    public void setMineralType(String mineralType) {
        this.mineralType = mineralType;
    }
    
    @Column(name="\"Grains_Number\"", precision=17, scale=17)
    public Double getGrainsNumber() {
        return this.grainsNumber;
    }
    
    public void setGrainsNumber(Double grainsNumber) {
        this.grainsNumber = grainsNumber;
    }
    
    @Column(name="\"chi_square_probability\"", precision=17, scale=17)
    public Double getChiSquareProbability() {
        return this.chiSquareProbability;
    }
    
    public void setChiSquareProbability(Double chiSquareProbability) {
        this.chiSquareProbability = chiSquareProbability;
    }
    
    @Column(name="\"Central_Age\"", precision=17, scale=17)
    public Double getCentralAge() {
        return this.centralAge;
    }
    
    public void setCentralAge(Double centralAge) {
        this.centralAge = centralAge;
    }
    
    @Column(name="\"Central_Age_Error\"", precision=17, scale=17)
    public Double getCentralAgeError() {
        return this.centralAgeError;
    }
    
    public void setCentralAgeError(Double centralAgeError) {
        this.centralAgeError = centralAgeError;
    }
    
    @Column(name="\"Pooled_Age\"", precision=17, scale=17)
    public Double getPooledAge() {
        return this.pooledAge;
    }
    
    public void setPooledAge(Double pooledAge) {
        this.pooledAge = pooledAge;
    }
    
    @Column(name="\"Pooled_Age_Error\"", precision=17, scale=17)
    public Double getPooledAgeError() {
        return this.pooledAgeError;
    }
    
    public void setPooledAgeError(Double pooledAgeError) {
        this.pooledAgeError = pooledAgeError;
    }
    
    @Column(name="\"mean_track_length\"", precision=17, scale=17)
    public Double getMeanTrackLength() {
        return this.meanTrackLength;
    }
    
    public void setMeanTrackLength(Double meanTrackLength) {
        this.meanTrackLength = meanTrackLength;
    }
    
    @Column(name="\"Length_Error\"", precision=17, scale=17)
    public Double getLengthError() {
        return this.lengthError;
    }
    
    public void setLengthError(Double lengthError) {
        this.lengthError = lengthError;
    }
    
    @Column(name="\"U_Th_He_Age\"", precision=17, scale=17)
    public Double getUThHeAge() {
        return this.UThHeAge;
    }
    
    public void setUThHeAge(Double UThHeAge) {
        this.UThHeAge = UThHeAge;
    }
    
    @Column(name="\"U_Th_He_Age_Error\"", precision=17, scale=17)
    public Double getUThHeAgeError() {
        return this.UThHeAgeError;
    }
    
    public void setUThHeAgeError(Double UThHeAgeError) {
        this.UThHeAgeError = UThHeAgeError;
    }
    
    @Column(name="\"ArticleRef\"")
    public String getArticleRef() {
        return this.articleRef;
    }
    
    public void setArticleRef(String articleRef) {
        this.articleRef = articleRef;
    }
    
    @Column(name="\"ArticleDOI\"")
    public String getArticleDoi() {
        return this.articleDoi;
    }
    
    public void setArticleDoi(String articleDoi) {
        this.articleDoi = articleDoi;
    }




}


