# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDlg(object):
    def setupUi(self, loginDlg):
        loginDlg.setObjectName("loginDlg")
        loginDlg.resize(793, 490)
        font = QtGui.QFont()
        font.setPointSize(12)
        loginDlg.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/DDE-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginDlg.setWindowIcon(icon)
        loginDlg.setStyleSheet("QMainWindow{\n"
"    font-family:\"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color:#f0f0f0;\n"
"    background:#125b4e;\n"
"}\n"
"QMainWindow#MainWindow{\n"
"    background:#125b4e;\n"
"}\n"
"\n"
"\n"
"\n"
"QStatusBar{\n"
"    color:#fff;\n"
"}\n"
"QStatusBar QLabel{\n"
"    color:#fff;\n"
"}\n"
"QStatusBar::item{\n"
"    border: 0px\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#fff;\n"
"}\n"
"\n"
"QDateTimeEdit, QLineEdit, QTextEdit, QPlainTextEdit{\n"
"    color:#fff;\n"
"    height:20px;\n"
"    padding-left:10px; \n"
"    background:transparent;\n"
"    border:none;\n"
"    border:1px solid #67968d;\n"
"}\n"
"\n"
"QDateTimeEdit::focus, QLineEdit::focus, QTextEdit::focus, QPlainTextEdit::focus{\n"
"    border:1px solid #00fffb;\n"
"}\n"
"\n"
"QDateTimeEdit:hover{\n"
"    background: #1f6155;\n"
"    color:#f2f2f2;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    alternate-background-color: #125b4e;\n"
"    background-color: #67968d;\n"
"}\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"    color: #67968d;\n"
"    font: 9px simHei;\n"
"}\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{\n"
"    background-color: #FFF;\n"
"}\n"
"\n"
"QTextEdit::focus{\n"
"    border:1px solid #00fffb;\n"
"}\n"
"QGroupBox::title {\n"
"    color:#fff;\n"
"}\n"
"QGroupBox QLineEdit{\n"
"    height:20px;\n"
"    padding-left:10px; \n"
"    background:transparent;\n"
"    border:none;\n"
"    border-bottom:1px solid #67968d;\n"
"}\n"
"\n"
"QDialog{\n"
"    background:#125b4e;\n"
"}\n"
"QDialog QLabel{\n"
"    color:#f0f0f0;\n"
"}\n"
"\n"
"QSplitter::handle{\n"
"    background-color:#125b4e;\n"
"}\n"
"\n"
"QComboBox{\n"
"    color:#fff;\n"
"    height:20px;\n"
"    padding-left:10px; \n"
"    background:transparent;\n"
"    border: 1px solid #67968d; \n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;   \n"
"    subcontrol-position: top right; \n"
"    width: 15px; \n"
"    border-left: 1px solid #67968d; \n"
"    image: url(\":/res/home/combo_drop.png\") \n"
"}\n"
"QComboBox::drop-down:hover {\n"
"    background: #00fffb;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;\n"
"    border: 1px solid #228c84;\n"
"    color: #FFFFFF;\n"
"    background-color: #07816e;\n"
"    selection-background-color: #1f6155; \n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 5px 10px; \n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: #1f6155;\n"
"}\n"
"\n"
"\n"
"QToolButton{\n"
"    padding:5px;\n"
"    border:none;\n"
"    background:transparent;\n"
"    color:#bebebe;\n"
"}\n"
"QToolButton:hover{\n"
"    background: #1f6155;\n"
"    color:#f2f2f2;\n"
"}\n"
"QToolButton:pressed{\n"
"    background: #34a897;\n"
"    color:#f2f2f2;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border:1px solid #4daa99;\n"
"    color:#e3e3e3;\n"
"    padding:4px 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #1f6155;\n"
"    color:#f2f2f2;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: #34a897;\n"
"    color:#f2f2f2;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"QListView{\n"
"    background:transparent;\n"
"    border:1px solid #228c84;\n"
"}\n"
"QListWidget{\n"
"    background:transparent;\n"
"    border:1px solid #228c84;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    padding:3px;\n"
"    border-radius:5px;\n"
"    color:#04ddd7;\n"
"    font:15px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QToolTip{\n"
"    border:0px solid #F0F0F0;\n"
"    padding:1px;\n"
"    color:#04ddd7;\n"
"\n"
"}\n"
"\n"
"\n"
"/*===================================== 表格 =================================*/\n"
"QTableView{\n"
"    outline:none;\n"
"    border-top:none;\n"
"    border-bottom-left-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"    alternate-background-color:#1b7065; \n"
"    selection-background-color:#01ae97;\n"
"    gridline-color:#0fa48e;\n"
"    color:#f2f2f2;\n"
"    background:transparent;\n"
"}\n"
"QHeaderView{\n"
"    border:none;\n"
"    border-bottom:1px solid #125b4e;\n"
"    background:#367b6e;\n"
"}\n"
"QHeaderView::section{\n"
"    background:transparent;\n"
"    color:#f2f2f2;\n"
"}\n"
"\n"
"\n"
"/*===================================== 树 =================================*/\n"
"QTreeView{\n"
"    show-decoration-selected:1;\n"
"    border:none; \n"
"    background:transparent;\n"
"}\n"
"QTreeView::item{\n"
"    height: 25px;\n"
"    color:#eaecec;    \n"
"    border:none;\n"
"    background:transparent;\n"
"}\n"
"\n"
"QTreeView::item:selected:active{  \n"
"    color:f2f2f2;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active{   \n"
"    color:#f2f2f2;    \n"
"}\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings{\n"
"    border-image:none;\n"
"    image:url(\":/res/home/tree_right.png\");\n"
"}\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings{\n"
"    border-image:none;\n"
"    image:url(\":/res/home/tree_bottom.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked {\n"
"    image: url(\":/res/home/tree_uncheck.png\");\n"
"}\n"
"QTreeView::indicator:checked {\n"
"    image: url(\":/res/home/tree_check.png\");\n"
"}\n"
"QTreeView::item:hover, QTreeView::branch:hover{\n"
"    background:#1f6155;\n"
"}\n"
"QTreeView::item:selected, QTreeView::branch:selected{\n"
"    background:#34a897;\n"
"    color:f2f2f2;\n"
"}\n"
"\n"
"\n"
"/*===================================== Tab =================================*/\n"
"QTabWidget#tabWidget{\n"
"    background:transparent;\n"
"}\n"
"QTabWidget::pane{\n"
"    border-top: 1px solid;\n"
"    border-color: transparent;\n"
"    top:-1px;\n"
"}\n"
"QTabBar::tab {\n"
"    min-width:85px;\n"
"    min-height:26px;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #e2e2e2;\n"
"    font:20px \"Microsoft YaHei\" ;\n"
"}\n"
"QTabBar::tab:selected{\n"
"    min-width:85px;\n"
"    min-height:25px;\n"
"    color: #000;\n"
"    border: 0px solid;\n"
"    background:#00fffb;\n"
"    font:20px \"Microsoft YaHei\" ;\n"
"}\n"
"\n"
"/*===================================== 垂直滚动条 =================================*/\n"
"/*设置垂直滚动条基本样式*/\n"
"QScrollBar:vertical {\n"
"    width: 14px;\n"
"    background: rgba(0,0,0,0%);\n"
"    margin: 0px,0px,0px,0px;\n"
"    /*留出9px给上面和下面的箭头*/\n"
"    padding-top: 9px;\n"
"    padding-bottom: 9px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    width: 14px;\n"
"    background: #238d71; /* #176857;rgba(0,0,0,25%); */\n"
"    /*滚动条两端变成椭圆 */\n"
"    border-radius: 14px;\n"
"    min-height: 20;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    width: 14px;\n"
"    /*鼠标放到滚动条上的时候，颜色变深*/\n"
"    background:  #238d71;  /*rgba(0,0,0,50%);*/\n"
"    border-radius: 12px;\n"
"    min-height: 20;\n"
"}\n"
"\n"
"/*这个应该是设置下箭头的，3.png就是箭头*/\n"
"QScrollBar::add-line:vertical \n"
"{\n"
"    height: 9px;\n"
"    width: 14px;\n"
"    border-image: url(:/res/down-arrow.png);\n"
"    subcontrol-position: bottom;\n"
"}\n"
"\n"
"/*设置上箭头 */\n"
"QScrollBar::sub-line:vertical \n"
"{\n"
"    height: 9px;\n"
"    width: 14px;\n"
"    border-image: url(:/res/up-arrow.png);\n"
"    subcontrol-position: top;\n"
"}\n"
"\n"
"/*当鼠标放到下箭头上的时候 */\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"    height: 9px;\n"
"    width: 14px;\n"
"    border-image: url(:/res/down-arrow.png);\n"
"    subcontrol-position: bottom;\n"
"}\n"
"\n"
"/*当鼠标放到下箭头上的时候*/\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"    height: 9px;\n"
"    width: 14px;\n"
"    border-image: url(:/res/up-arrow.png);\n"
"    subcontrol-position: top;\n"
"}\n"
"\n"
"/*当滚动条滚动的时候，上面的部分和下面的部分*/\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #176857;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical \n"
"{\n"
"    background: #176857; /* #238d71;*/\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QScrollArea#scrollArea{\n"
"    background:transparent;\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"QWidget#scrollAreaWidgetContents{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea#scrollArea{\n"
"    background:transparent;\n"
"\n"
"    QScrollBar:vertical{  /*//滚动条主体部分(滑道)*/\n"
"        min-width: 10;/*//滑道最小宽度*/\n"
"        min-height:100;/*//滑道最小高度*/\n"
"        border-radius:5px;/*//滑道圆角*/\n"
"        background-color:rgb(200,200,200);/*//滑轨的颜色*/\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical{  /*//滑块主体*/\n"
"        border-radius:5px;/*//滑块圆形角度*/\n"
"        width: 10;/*//滑块宽度*/\n"
"        border-radius:5px;/*//滑道圆角*/\n"
"        background-color:rgb(50,50,20);/*//滑块颜色*/\n"
"    }  \n"
"\n"
"    QScrollBar::handle:vertical:hover{  /*//鼠标放在上面时*/\n"
"        width: 10;/*//滑块宽度*/\n"
"        border-radius:5px;/*//滑道圆角*/\n"
"        background-color:rgba(0,0,0,50%);/*//滑块颜色变化*/\n"
"    }\n"
"    \n"
"}\n"
"")
        loginDlg.setModal(False)
        self.btnLogin = QtWidgets.QPushButton(loginDlg)
        self.btnLogin.setGeometry(QtCore.QRect(400, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setDefault(True)
        self.btnLogin.setObjectName("btnLogin")
        self.btnCancel = QtWidgets.QPushButton(loginDlg)
        self.btnCancel.setGeometry(QtCore.QRect(590, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.layoutWidget = QtWidgets.QWidget(loginDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 771, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblWorldMap = QtWidgets.QLabel(self.layoutWidget)
        self.lblWorldMap.setMinimumSize(QtCore.QSize(320, 180))
        self.lblWorldMap.setMaximumSize(QtCore.QSize(320, 180))
        self.lblWorldMap.setText("")
        self.lblWorldMap.setTextFormat(QtCore.Qt.RichText)
        self.lblWorldMap.setPixmap(QtGui.QPixmap("res/worldmap.gif"))
        self.lblWorldMap.setScaledContents(True)
        self.lblWorldMap.setObjectName("lblWorldMap")
        self.horizontalLayout_3.addWidget(self.lblWorldMap)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 30, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtUser = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUser.sizePolicy().hasHeightForWidth())
        self.txtUser.setSizePolicy(sizePolicy)
        self.txtUser.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtUser.setFont(font)
        self.txtUser.setClearButtonEnabled(True)
        self.txtUser.setObjectName("txtUser")
        self.horizontalLayout.addWidget(self.txtUser)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, 30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txtPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtPassword.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setInputMask("")
        self.txtPassword.setText("")
        self.txtPassword.setMaxLength(18)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setClearButtonEnabled(True)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout_2.addWidget(self.txtPassword)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(1, 1)
        self.frame = QtWidgets.QFrame(loginDlg)
        self.frame.setGeometry(QtCore.QRect(0, 0, 791, 161))
        self.frame.setStyleSheet("border-image:url(\"res/logo_header.png\");")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.chkRemember = QtWidgets.QCheckBox(loginDlg)
        self.chkRemember.setGeometry(QtCore.QRect(350, 380, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkRemember.setFont(font)
        self.chkRemember.setObjectName("chkRemember")
        self.chkAutoLogin = QtWidgets.QCheckBox(loginDlg)
        self.chkAutoLogin.setGeometry(QtCore.QRect(640, 380, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkAutoLogin.setFont(font)
        self.chkAutoLogin.setObjectName("chkAutoLogin")
        self.label = QtWidgets.QLabel(loginDlg)
        self.label.setGeometry(QtCore.QRect(20, 370, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(loginDlg)
        self.label_4.setGeometry(QtCore.QRect(20, 410, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(loginDlg)
        self.btnCancel.clicked.connect(loginDlg.close) # type: ignore
        self.btnLogin.clicked.connect(loginDlg.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loginDlg)

    def retranslateUi(self, loginDlg):
        _translate = QtCore.QCoreApplication.translate
        loginDlg.setWindowTitle(_translate("loginDlg", "DDE-OnePetrology"))
        self.btnLogin.setText(_translate("loginDlg", "Login"))
        self.btnCancel.setText(_translate("loginDlg", "Cancel"))
        self.label_2.setText(_translate("loginDlg", "User Account："))
        self.txtUser.setPlaceholderText(_translate("loginDlg", "Please input your email"))
        self.label_3.setText(_translate("loginDlg", "Password："))
        self.txtPassword.setPlaceholderText(_translate("loginDlg", "Please input your password"))
        self.chkRemember.setText(_translate("loginDlg", "Remember user and password"))
        self.chkAutoLogin.setText(_translate("loginDlg", "Auto Login"))
        self.label.setText(_translate("loginDlg", "<a style=\"color:white\"  href=\"https://petrology.deep-time.org/dspace/register\">Click me to register new user...</a>"))
        self.label_4.setText(_translate("loginDlg", "<a style=\"color:yellow\"  href=\"https://petrology.deep-time.org/dspace/forgot\">Forgot Password, click here...</a>"))
