# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_column_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColumnConfig(object):
    def setupUi(self, ColumnConfig):
        ColumnConfig.setObjectName("ColumnConfig")
        ColumnConfig.resize(1140, 35)
        ColumnConfig.setMinimumSize(QtCore.QSize(600, 35))
        ColumnConfig.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        ColumnConfig.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(ColumnConfig)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(ColumnConfig)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.lblDesc = QtWidgets.QLabel(ColumnConfig)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lblDesc.setFont(font)
        self.lblDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout.addWidget(self.lblDesc, 0, 1, 1, 1)
        self.lblType = QtWidgets.QLabel(ColumnConfig)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lblType.setFont(font)
        self.lblType.setStyleSheet("color: rgb(251, 255, 210);")
        self.lblType.setObjectName("lblType")
        self.gridLayout.addWidget(self.lblType, 0, 2, 1, 1)
        self.chkDefault = QtWidgets.QCheckBox(ColumnConfig)
        self.chkDefault.setObjectName("chkDefault")
        self.gridLayout.addWidget(self.chkDefault, 0, 3, 1, 1)
        self.ldtDefault = QtWidgets.QLineEdit(ColumnConfig)
        self.ldtDefault.setEnabled(False)
        self.ldtDefault.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ldtDefault.setObjectName("ldtDefault")
        self.gridLayout.addWidget(self.ldtDefault, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(ColumnConfig)
        self.label.setStyleSheet("color: rgb(255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1)
        self.comboNullProcess = QtWidgets.QComboBox(ColumnConfig)
        self.comboNullProcess.setObjectName("comboNullProcess")
        self.comboNullProcess.addItem("")
        self.comboNullProcess.addItem("")
        self.gridLayout.addWidget(self.comboNullProcess, 0, 6, 1, 1)
        self.ldtNullValue = QtWidgets.QLineEdit(ColumnConfig)
        self.ldtNullValue.setEnabled(True)
        self.ldtNullValue.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ldtNullValue.setObjectName("ldtNullValue")
        self.gridLayout.addWidget(self.ldtNullValue, 0, 7, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(ColumnConfig)
        self.chkDefault.toggled['bool'].connect(self.ldtDefault.setEnabled)
        self.chkDefault.toggled['bool'].connect(self.ldtDefault.setVisible)
        QtCore.QMetaObject.connectSlotsByName(ColumnConfig)

    def retranslateUi(self, ColumnConfig):
        _translate = QtCore.QCoreApplication.translate
        ColumnConfig.setWindowTitle(_translate("ColumnConfig", "Form"))
        self.lblName.setText(_translate("ColumnConfig", "TextLabel"))
        self.lblDesc.setText(_translate("ColumnConfig", "TextLabel"))
        self.lblType.setText(_translate("ColumnConfig", "TextLabel"))
        self.chkDefault.setText(_translate("ColumnConfig", "Use Default"))
        self.label.setText(_translate("ColumnConfig", "Null Process："))
        self.comboNullProcess.setItemText(0, _translate("ColumnConfig", "Drop Only"))
        self.comboNullProcess.setItemText(1, _translate("ColumnConfig", "Fill Value"))
