# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dfColumnMapping.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dfColumnMapping(object):
    def setupUi(self, dfColumnMapping):
        dfColumnMapping.setObjectName("dfColumnMapping")
        dfColumnMapping.resize(963, 639)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(dfColumnMapping)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(dfColumnMapping)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.targetDataType = QtWidgets.QWidget()
        self.targetDataType.setGeometry(QtCore.QRect(0, 0, 923, 134))
        self.targetDataType.setStyleSheet("   font-family:\"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color:#f0f0f0;\n"
"    background:#125b4e;\n"
"   border: 1px solid #228c84;")
        self.targetDataType.setObjectName("targetDataType")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.targetDataType)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.targetLayout = QtWidgets.QVBoxLayout()
        self.targetLayout.setSpacing(3)
        self.targetLayout.setObjectName("targetLayout")
        self.verticalLayout.addLayout(self.targetLayout)
        self.scrollArea.setWidget(self.targetDataType)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 20, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnDoPlotting = QtWidgets.QPushButton(self.groupBox_2)
        self.btnDoPlotting.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";")
        self.btnDoPlotting.setObjectName("btnDoPlotting")
        self.verticalLayout_2.addWidget(self.btnDoPlotting)
        self.btnSaveData = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSaveData.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";")
        self.btnSaveData.setObjectName("btnSaveData")
        self.verticalLayout_2.addWidget(self.btnSaveData)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(dfColumnMapping)
        QtCore.QMetaObject.connectSlotsByName(dfColumnMapping)

    def retranslateUi(self, dfColumnMapping):
        _translate = QtCore.QCoreApplication.translate
        dfColumnMapping.setWindowTitle(_translate("dfColumnMapping", "Form"))
        self.groupBox.setTitle(_translate("dfColumnMapping", "Target Data Type"))
        self.groupBox_2.setTitle(_translate("dfColumnMapping", "Dataframe Column  Mapping"))
        self.btnDoPlotting.setText(_translate("dfColumnMapping", "Do Plotting"))
        self.btnSaveData.setText(_translate("dfColumnMapping", "Save Data"))
