# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dfview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DfView(object):
    def setupUi(self, DfView):
        DfView.setObjectName("DfView")
        DfView.resize(579, 533)
        self.verticalLayout = QtWidgets.QVBoxLayout(DfView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(DfView)
        self.tableView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.actionSave_Excel = QtWidgets.QAction(DfView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Excel.setIcon(icon)
        self.actionSave_Excel.setObjectName("actionSave_Excel")

        self.retranslateUi(DfView)
        QtCore.QMetaObject.connectSlotsByName(DfView)

    def retranslateUi(self, DfView):
        _translate = QtCore.QCoreApplication.translate
        DfView.setWindowTitle(_translate("DfView", "Form"))
        self.actionSave_Excel.setText(_translate("DfView", "Save Excel"))
        self.actionSave_Excel.setToolTip(_translate("DfView", "Save to excel file"))
