# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_field_fiter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FieldFilterForm(object):
    def setupUi(self, FieldFilterForm):
        FieldFilterForm.setObjectName("FieldFilterForm")
        FieldFilterForm.resize(599, 51)
        FieldFilterForm.setMaximumSize(QtCore.QSize(32768, 69))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        FieldFilterForm.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(FieldFilterForm)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(FieldFilterForm)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboField = QtWidgets.QComboBox(self.groupBox)
        self.comboField.setObjectName("comboField")
        self.horizontalLayout.addWidget(self.comboField)
        self.comboOp = QtWidgets.QComboBox(self.groupBox)
        self.comboOp.setObjectName("comboOp")
        self.horizontalLayout.addWidget(self.comboOp)
        self.ldtValue = QtWidgets.QLineEdit(self.groupBox)
        self.ldtValue.setObjectName("ldtValue")
        self.horizontalLayout.addWidget(self.ldtValue)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.btnAdd = QtWidgets.QPushButton(FieldFilterForm)
        self.btnAdd.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnAdd.setStyleSheet("color: rgb(0, 255, 0);")
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.comboJoin = QtWidgets.QComboBox(FieldFilterForm)
        self.comboJoin.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboJoin.setFont(font)
        self.comboJoin.setMaxVisibleItems(2)
        self.comboJoin.setMinimumContentsLength(0)
        self.comboJoin.setObjectName("comboJoin")
        self.comboJoin.addItem("")
        self.comboJoin.addItem("")
        self.horizontalLayout_2.addWidget(self.comboJoin)
        self.btnRemove = QtWidgets.QPushButton(FieldFilterForm)
        self.btnRemove.setStyleSheet("color: rgb(255, 0, 0);")
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)

        self.retranslateUi(FieldFilterForm)
        QtCore.QMetaObject.connectSlotsByName(FieldFilterForm)

    def retranslateUi(self, FieldFilterForm):
        _translate = QtCore.QCoreApplication.translate
        FieldFilterForm.setWindowTitle(_translate("FieldFilterForm", "Form"))
        self.ldtValue.setToolTip(_translate("FieldFilterForm", "input the value"))
        self.ldtValue.setPlaceholderText(_translate("FieldFilterForm", "input the value"))
        self.btnAdd.setText(_translate("FieldFilterForm", "Add(+)"))
        self.comboJoin.setItemText(0, _translate("FieldFilterForm", "And"))
        self.comboJoin.setItemText(1, _translate("FieldFilterForm", "Or"))
        self.btnRemove.setText(_translate("FieldFilterForm", "Delete(-)"))
