# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_knowledgetree_root.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KnowledgeTree4Root(object):
    def setupUi(self, KnowledgeTree4Root):
        KnowledgeTree4Root.setObjectName("KnowledgeTree4Root")
        KnowledgeTree4Root.resize(1156, 576)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(KnowledgeTree4Root)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(KnowledgeTree4Root)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/DDE-logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.treeView = KTreeWidget(self.groupBox)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnPreview = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPreview.setIcon(icon)
        self.btnPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout_2.addWidget(self.btnPreview)
        self.btnSaveExcel = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveExcel.setIcon(icon1)
        self.btnSaveExcel.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSaveExcel.setObjectName("btnSaveExcel")
        self.horizontalLayout_2.addWidget(self.btnSaveExcel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.stackPage1 = QtWidgets.QWidget()
        self.stackPage1.setObjectName("stackPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stackPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = DfViewWidget(self.stackPage1)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.stackedWidget_2.addWidget(self.stackPage1)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(KnowledgeTree4Root)
        QtCore.QMetaObject.connectSlotsByName(KnowledgeTree4Root)

    def retranslateUi(self, KnowledgeTree4Root):
        _translate = QtCore.QCoreApplication.translate
        KnowledgeTree4Root.setWindowTitle(_translate("KnowledgeTree4Root", "Form"))
        self.textBrowser.setHtml(_translate("KnowledgeTree4Root", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   The knowledge tree editing of DDE onepetroleum is divided into the following steps:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   1) First create the root node. At present, the root node type supports two types: entity and enum, which represent entity class and classification enumeration value respectively.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   2) Then add subordinate classifications and child nodes level by level. Dir represents grouping and prop represents leaf nodes (representing graph, text and number).</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   3) For classification enumeration values, expressions are supported. When the operation value of the expression is true, it represents that it belongs to the classification.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">  4) When the value is relax to, it represents the association of another object, that is, the entity on another table.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   5) After the design is completed, it can be previewed or exported as an excel template for data collection.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   DDE OnePetrology的知识树编辑分为如下步骤：</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   1）首先创建根节点。根节点类型目前支持两类:ENTITY和ENUM，分别代表实体类和分类枚举取值。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   2）然后逐级添加下属分类和子节点。其中DIR代表的是分组，PROP代表的是叶子节点（表示图、文、数）。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   3）针对分类枚举取值，支持表达式，当表达式运算值为True时，代表属于该分类。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   4）取值为RELATE TO类型时，代表另外一种对象的关联，即关联到另外一个表上的实体。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   5）设计完成之后，可以预览，也可以导出为excel模板用于收集数据。</span></p></body></html>"))
        self.groupBox.setTitle(_translate("KnowledgeTree4Root", "Knowledge Tree Design"))
        self.label_2.setText(_translate("KnowledgeTree4Root", "TIPS: Refresh and then can add root Entity or Enum..."))
        self.btnPreview.setText(_translate("KnowledgeTree4Root", "Preview"))
        self.btnSaveExcel.setText(_translate("KnowledgeTree4Root", "Save Excel"))
from DfViewWidget import DfViewWidget
from KTreeWidget import KTreeWidget
