# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_knowledgetree_my.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KnowledgeTree4My(object):
    def setupUi(self, KnowledgeTree4My):
        KnowledgeTree4My.setObjectName("KnowledgeTree4My")
        KnowledgeTree4My.resize(1324, 648)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(KnowledgeTree4My)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(KnowledgeTree4My)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/edit.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.treeView = KTreeWidget4My(self.groupBox)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tbtnCopyRoot = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/entity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtnCopyRoot.setIcon(icon)
        self.tbtnCopyRoot.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbtnCopyRoot.setObjectName("tbtnCopyRoot")
        self.horizontalLayout_2.addWidget(self.tbtnCopyRoot)
        self.btnPreview = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPreview.setIcon(icon1)
        self.btnPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout_2.addWidget(self.btnPreview)
        self.btnSaveExcel = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveExcel.setIcon(icon2)
        self.btnSaveExcel.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSaveExcel.setObjectName("btnSaveExcel")
        self.horizontalLayout_2.addWidget(self.btnSaveExcel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.stackPage1 = QtWidgets.QWidget()
        self.stackPage1.setObjectName("stackPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stackPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = DfViewWidget(self.stackPage1)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.stackedWidget_2.addWidget(self.stackPage1)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(KnowledgeTree4My)
        QtCore.QMetaObject.connectSlotsByName(KnowledgeTree4My)

    def retranslateUi(self, KnowledgeTree4My):
        _translate = QtCore.QCoreApplication.translate
        KnowledgeTree4My.setWindowTitle(_translate("KnowledgeTree4My", "Form"))
        self.textBrowser.setHtml(_translate("KnowledgeTree4My", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   A custom knowledge tree is a specialized knowledge tree for research. Discipline experts can cut and modify from the common root knowledge tree to form a discipline specific knowledge system / knowledge tree.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   1) The user-defined knowledge tree is copied from the root. One user does not affect each other;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   2) The modification of the user-defined knowledge tree will not be reflected in the root public knowledge tree. If necessary, please contact the administrator to submit it. After approval, you can see it in the root public knowledge tree;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   3) The editing rules of user-defined knowledge tree are the same as those of root knowledge. Please refer to relevant materials for editing.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   自定义知识树，是专门为学科研究专家提供的功能。学科专家可以从公用的ROOT知识树上进行裁剪和修改，形成学科专用的知识体系/知识树。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   1）自定义知识树，来自于从ROOT的复制，一个用户一个，互不影响；</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   2）对自定义知识树的修改，不会体现到ROOT公用知识树中，如果需要请联系管理员进行提交，经过核准后方可在ROOT公用知识树中看到；</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">   3）自定义知识树的编辑和ROOT知识的编辑规则相同，请参阅相关材料进行编辑。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.groupBox.setTitle(_translate("KnowledgeTree4My", "My Knowledge Tree Design"))
        self.label_2.setText(_translate("KnowledgeTree4My", "TIPS: 1) Copy from Root is the first step; 2)Refresh and then can add root Entity or Enum..."))
        self.tbtnCopyRoot.setText(_translate("KnowledgeTree4My", "Copy from Root"))
        self.btnPreview.setText(_translate("KnowledgeTree4My", "Preview"))
        self.btnSaveExcel.setText(_translate("KnowledgeTree4My", "Save Excel"))
from DfViewWidget import DfViewWidget
from KTreeWidget4My import KTreeWidget4My
