# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_process_excel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessExcel(object):
    def setupUi(self, ProcessExcel):
        ProcessExcel.setObjectName("ProcessExcel")
        ProcessExcel.resize(817, 670)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ProcessExcel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(ProcessExcel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.groupBox)
        self.treeView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.widget = ExcelProcessWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.splitter)

        self.retranslateUi(ProcessExcel)
        QtCore.QMetaObject.connectSlotsByName(ProcessExcel)

    def retranslateUi(self, ProcessExcel):
        _translate = QtCore.QCoreApplication.translate
        ProcessExcel.setWindowTitle(_translate("ProcessExcel", "Form"))
        self.groupBox.setTitle(_translate("ProcessExcel", "Repository Excel Files"))
from ExcelProcessWidget import ExcelProcessWidget
