# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_private_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrivateData(object):
    def setupUi(self, PrivateData):
        PrivateData.setObjectName("PrivateData")
        PrivateData.resize(1212, 628)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        PrivateData.setFont(font)
        PrivateData.setStyleSheet("\n"
"\n"
"/*===================================== Tab =================================*/\n"
"QTabWidget#tabWidget{\n"
"    background:transparent;\n"
"}\n"
"QTabWidget::pane{\n"
"    border-top: 1px solid;\n"
"    border-color: transparent;\n"
"    top:-1px;\n"
"}\n"
"QTabBar::tab {\n"
"    min-width:85px;\n"
"    min-height:16px;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #e2e2e2; \n"
"    font:12px \"Microsoft YaHei\" ;\n"
"}\n"
"QTabBar::tab:selected{\n"
"    min-width:85px;\n"
"    min-height:18px;\n"
"    color: #000;\n"
"    border: 0px solid;\n"
"    background:#00fffb;\n"
"    font:14px \"Microsoft YaHei\" ;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PrivateData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(PrivateData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboEntity = QtWidgets.QComboBox(PrivateData)
        self.comboEntity.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboEntity.setFont(font)
        self.comboEntity.setObjectName("comboEntity")
        self.horizontalLayout_2.addWidget(self.comboEntity)
        self.btnRefresh = QtWidgets.QPushButton(PrivateData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btnRefresh.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_2.addWidget(self.btnRefresh)
        self.btnClear = QtWidgets.QPushButton(PrivateData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btnClear.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon1)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_2.addWidget(self.btnClear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnFetch = QtWidgets.QPushButton(PrivateData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btnFetch.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFetch.setIcon(icon2)
        self.btnFetch.setObjectName("btnFetch")
        self.horizontalLayout_2.addWidget(self.btnFetch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.combDf = QtWidgets.QComboBox(PrivateData)
        self.combDf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.combDf.setFont(font)
        self.combDf.setObjectName("combDf")
        self.horizontalLayout_2.addWidget(self.combDf)
        self.btnDuplicateCheck = QtWidgets.QPushButton(PrivateData)
        self.btnDuplicateCheck.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.btnDuplicateCheck.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDuplicateCheck.setIcon(icon3)
        self.btnDuplicateCheck.setObjectName("btnDuplicateCheck")
        self.horizontalLayout_2.addWidget(self.btnDuplicateCheck)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(PrivateData)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.queryFilterWidget = QueryFilterWidget(self.groupBox)
        self.queryFilterWidget.setObjectName("queryFilterWidget")
        self.horizontalLayout.addWidget(self.queryFilterWidget)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(PrivateData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(PrivateData)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PrivateData)

    def retranslateUi(self, PrivateData):
        _translate = QtCore.QCoreApplication.translate
        PrivateData.setWindowTitle(_translate("PrivateData", "Form"))
        self.label.setText(_translate("PrivateData", "Select Knowledge Entity:"))
        self.btnRefresh.setText(_translate("PrivateData", "Refresh"))
        self.btnClear.setText(_translate("PrivateData", "Clear"))
        self.btnFetch.setText(_translate("PrivateData", "Fetch Data"))
        self.btnDuplicateCheck.setText(_translate("PrivateData", "Duplicate Checking"))
        self.groupBox.setTitle(_translate("PrivateData", "Query Params"))
from QueryFilterWidget import QueryFilterWidget
