# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TraditionalTree.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TraditionalTree(object):
    def setupUi(self, TraditionalTree):
        TraditionalTree.setObjectName("TraditionalTree")
        TraditionalTree.resize(333, 684)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TraditionalTree)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRefresh = QtWidgets.QPushButton(TraditionalTree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setMinimumSize(QtCore.QSize(50, 30))
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.btnAdd = QtWidgets.QPushButton(TraditionalTree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnModify = QtWidgets.QPushButton(TraditionalTree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnModify.sizePolicy().hasHeightForWidth())
        self.btnModify.setSizePolicy(sizePolicy)
        self.btnModify.setMinimumSize(QtCore.QSize(0, 30))
        self.btnModify.setObjectName("btnModify")
        self.horizontalLayout.addWidget(self.btnModify)
        self.btnDelete = QtWidgets.QPushButton(TraditionalTree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(TraditionalTree)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.treeView = QtWidgets.QTreeView(TraditionalTree)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TraditionalTree)
        QtCore.QMetaObject.connectSlotsByName(TraditionalTree)

    def retranslateUi(self, TraditionalTree):
        _translate = QtCore.QCoreApplication.translate
        TraditionalTree.setWindowTitle(_translate("TraditionalTree", "Form"))
        self.btnRefresh.setText(_translate("TraditionalTree", "刷 新"))
        self.btnAdd.setText(_translate("TraditionalTree", "添 加"))
        self.btnModify.setText(_translate("TraditionalTree", "修 改"))
        self.btnDelete.setText(_translate("TraditionalTree", "删 除"))
