# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_uploadTableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableUploadWidget(object):
    def setupUi(self, TableUploadWidget):
        TableUploadWidget.setObjectName("TableUploadWidget")
        TableUploadWidget.resize(453, 60)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TableUploadWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDelete = QtWidgets.QPushButton(TableUploadWidget)
        self.btnDelete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnUpload = QtWidgets.QPushButton(TableUploadWidget)
        self.btnUpload.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpload.setIcon(icon1)
        self.btnUpload.setObjectName("btnUpload")
        self.horizontalLayout.addWidget(self.btnUpload)
        self.progressBar = QtWidgets.QProgressBar(TableUploadWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.btnPreview = QtWidgets.QPushButton(TableUploadWidget)
        self.btnPreview.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPreview.setIcon(icon2)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout.addWidget(self.btnPreview)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(TableUploadWidget)
        QtCore.QMetaObject.connectSlotsByName(TableUploadWidget)

    def retranslateUi(self, TableUploadWidget):
        _translate = QtCore.QCoreApplication.translate
        TableUploadWidget.setWindowTitle(_translate("TableUploadWidget", "Form"))
        self.btnDelete.setToolTip(_translate("TableUploadWidget", "删除，不上传本文件"))
        self.btnUpload.setToolTip(_translate("TableUploadWidget", "执行上传"))
